export interface BlogBlock {
  type: 'p' | 'h2' | 'ul' | 'book' | 'tip';
  text?: string;
  items?: string[];
  title?: string;
  author?: string;
  note?: string;
}

export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  category: string;
  readTime: string;
  date: string;
  content: BlogBlock[];
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: 'top-25-free-programming-books-2026',
    title: 'Top 25 Free Programming Books in 2026',
    description: 'The best free programming books for every language and skill level — from Python beginners to systems programming, all legally free to read and download.',
    category: 'Technology',
    readTime: '12 min',
    date: 'Jan 15, 2026',
    content: [
      { type: 'p', text: 'Programming books are expensive — a single new O\'Reilly title often costs $40–60, and a full learning path can run past $300. The good news: some of the most respected programming books ever written are completely free, released by their authors under open licenses or published openly on the web. This list collects 25 of the best, organized by where you are in your journey.' },
      { type: 'h2', text: 'For complete beginners' },
      { type: 'book', title: 'Automate the Boring Stuff with Python', author: 'Al Sweigart', note: 'The single best first programming book. Free to read online, teaches Python through practical tasks — renaming files, filling forms, scraping websites — instead of abstract theory.' },
      { type: 'book', title: 'Python Crash Course', author: 'Eric Matthes', note: 'A structured, project-driven introduction. Pairs well with Automate the Boring Stuff: read this for foundations, that for practical wins.' },
      { type: 'book', title: 'Eloquent JavaScript', author: 'Marijn Haverbeke', note: 'The classic free introduction to JavaScript and programming in general, with interactive exercises built into the online edition.' },
      { type: 'p', text: 'Start with exactly one of these, finish it, and build something small before adding more books. Collecting books is not the same as learning.' },
      { type: 'h2', text: 'Leveling up: intermediate essentials' },
      { type: 'book', title: 'You Don\'t Know JS', author: 'Kyle Simpson', note: 'A free book series that goes deep on how JavaScript actually works — scope, closures, prototypes, async. Read after your first project, not before.' },
      { type: 'book', title: 'The Linux Command Line', author: 'William Shotts', note: 'Free from the author. Every developer eventually needs the terminal; this is the gentlest thorough introduction.' },
      { type: 'book', title: 'Pro Git', author: 'Scott Chacon & Ben Straub', note: 'The official Git book, free forever. Chapters 1–3 cover 90% of what you\'ll use daily.' },
      { type: 'book', title: 'Structure and Interpretation of Computer Programs', author: 'Abelson & Sussman', note: 'MIT\'s legendary text, free online. Harder than everything above, and worth it — it changes how you think about programs.' },
      { type: 'h2', text: 'Specialization: data, ML, and systems' },
      { type: 'book', title: 'Deep Learning', author: 'Ian Goodfellow, Yoshua Bengio & Aaron Courville', note: 'The standard deep learning reference, free on the authors\' site. Requires linear algebra and calculus.' },
      { type: 'book', title: 'The TypeScript Handbook', author: 'Microsoft', note: 'The official, always-current way to learn TypeScript, maintained free by the language team itself.' },
      { type: 'ul', items: [
        'Operating Systems: Three Easy Pieces — the free OS textbook used by dozens of universities',
        'High Performance Browser Networking (Ilya Grigorik) — free from O\'Reilly, essential for web performance',
        'The Rust Book — the official free way to learn Rust',
        'Dive Into Deep Learning — free, code-first ML with runnable notebooks',
        'Crafting Interpreters (Robert Nystrom) — free online; build two programming languages from scratch',
      ] },
      { type: 'h2', text: 'How to actually find these' },
      { type: 'p', text: 'Every book above is searchable on ANYFREEBOOK — we aggregate Open Library, Project Gutenberg, Internet Archive, Google Books, and open-access repositories in one search. Type the title, check the source badge, and read online or download in the formats the source offers. No sign-up needed.' },
      { type: 'tip', text: 'Pick one book. Finish it. Build a small project with what you learned. Then come back for the next one — that loop beats any 25-book reading marathon.' },
    ],
  },
  {
    slug: 'free-alternatives-campbell-biology',
    title: 'Free Alternatives to Campbell Biology (Save $189)',
    description: 'Campbell Biology costs $189 new. These free, legal alternatives cover the same introductory biology material — used by real universities.',
    category: 'Sciences',
    readTime: '8 min',
    date: 'Jan 10, 2026',
    content: [
      { type: 'p', text: 'Campbell Biology is the standard first-year biology text at hundreds of universities, and a new copy costs about $189 — more than many students\' weekly budget. If your course follows the standard intro-biology sequence (cell biology, genetics, evolution, physiology, ecology), openly licensed textbooks cover the same ground for free.' },
      { type: 'h2', text: 'The best free replacement' },
      { type: 'book', title: 'Biology 2e (OpenStax)', author: 'Rice University', note: 'A complete, peer-reviewed intro biology textbook written specifically to match courses that use Campbell. Free PDF and web versions, professionally edited, with review questions per chapter. This is the one to get.' },
      { type: 'p', text: 'OpenStax is published by Rice University and funded by foundations precisely so students don\'t have to buy $200 textbooks. Their books are not scans or summaries — they are complete textbooks used officially at thousands of institutions.' },
      { type: 'h2', text: 'Free books for specific units' },
      { type: 'ul', items: [
        'Concepts of Biology (OpenStax) — a lighter one-semester version for non-majors',
        'Microbiology (OpenStax) — if your course leans micro',
        'Anatomy and Physiology (OpenStax) — for the physiology units',
        'On the Origin of Species (Darwin) — public domain on Project Gutenberg; still remarkably readable for the evolution unit',
      ] },
      { type: 'h2', text: 'How to study from a free textbook when your class uses Campbell' },
      { type: 'p', text: 'Chapter numbers won\'t match, so navigate by topic instead: your syllabus says "cell respiration," you read the cell respiration chapter. Free texts include the same figures-first explanations, and end-of-chapter questions map closely. For the handful of topics where your professor references specific Campbell figures, a library reserve copy fills the gap — most university libraries keep one.' },
      { type: 'tip', text: 'Search any of these titles on ANYFREEBOOK to get the direct source link — we aggregate OpenStax mirrors, Internet Archive, and Open Library in one search.' },
    ],
  },
  {
    slug: 'learn-machine-learning-free-reading-list',
    title: 'Learn Machine Learning for Free — Complete Reading List',
    description: 'A free, ordered reading path from ML beginner to practitioner: 15 books with estimated study times, all legally free.',
    category: 'Technology',
    readTime: '10 min',
    date: 'Jan 5, 2026',
    content: [
      { type: 'p', text: 'Machine learning has the best free literature of any technical field — the standard references are free because the researchers who wrote them wanted them read. The problem isn\'t finding free ML books; it\'s reading them in an order that doesn\'t crush you. Here\'s a path that works, with honest time estimates.' },
      { type: 'h2', text: 'Stage 1: Foundations (4–8 weeks)' },
      { type: 'book', title: 'Python Crash Course', author: 'Eric Matthes', note: 'Skip if you already write Python comfortably. Otherwise, everything downstream depends on this.' },
      { type: 'book', title: 'Mathematics for Machine Learning', author: 'Deisenroth, Faisal & Ong', note: 'Free from Cambridge University Press. Linear algebra, calculus, and probability — exactly the subset ML needs, no more.' },
      { type: 'h2', text: 'Stage 2: Core ML (6–10 weeks)' },
      { type: 'book', title: 'An Introduction to Statistical Learning', author: 'James, Witten, Hastie & Tibshirani', note: 'The most recommended first ML book on earth, free from the authors. Concepts first, math second, with labs in Python or R.' },
      { type: 'book', title: 'Dive Into Deep Learning', author: 'Zhang, Lipton, Li & Smola', note: 'Free and interactive — every concept comes with runnable code. The fastest route from "I know Python" to "I trained a network."' },
      { type: 'h2', text: 'Stage 3: Depth (ongoing)' },
      { type: 'book', title: 'Deep Learning', author: 'Goodfellow, Bengio & Courville', note: 'The reference text, free online. Read chapters as you need them rather than front to back.' },
      { type: 'book', title: 'The Elements of Statistical Learning', author: 'Hastie, Tibshirani & Friedman', note: 'The heavyweight older sibling of ISL, also free. Graduate level; treat it as an encyclopedia.' },
      { type: 'ul', items: [
        'Pattern Recognition and Machine Learning (Bishop) — free PDF released by Microsoft Research',
        'Reinforcement Learning: An Introduction (Sutton & Barto) — the standard RL text, free from the authors',
        'Speech and Language Processing (Jurafsky & Martin) — free drafts; the NLP standard',
        'Probabilistic Machine Learning (Murphy) — modern, comprehensive, free drafts online',
      ] },
      { type: 'h2', text: 'The honest advice' },
      { type: 'p', text: 'Most people fail this path by reading Stage 3 books first. ISL plus Dive Into Deep Learning, actually completed with the exercises, puts you ahead of the majority of self-taught ML learners. Total cost of the entire path above: $0.' },
      { type: 'tip', text: 'All of these are findable through ANYFREEBOOK search — we link you to the official free versions hosted by the authors and open repositories.' },
    ],
  },
  {
    slug: 'where-to-download-free-medical-textbooks',
    title: 'Where to Download Free Medical Textbooks Online',
    description: 'A complete guide to finding free, legal medical textbooks and references: anatomy, pharmacology, pathology, and the open-access sources that host them.',
    category: 'Medicine',
    readTime: '9 min',
    date: 'Dec 28, 2025',
    content: [
      { type: 'p', text: 'Medical textbooks are the most expensive books in education — $100–350 each, with a preclinical shelf easily passing $1,500. There is a real, legal free ecosystem, but you need to know which sources are legitimate. Everything below is legal and openly licensed or public access.' },
      { type: 'h2', text: 'The legitimate free sources' },
      { type: 'ul', items: [
        'OpenStax Anatomy & Physiology — a complete, peer-reviewed A&P textbook, free from Rice University',
        'NCBI Bookshelf — the U.S. National Library of Medicine hosts full free books including StatPearls, essentially a free encyclopedic clinical reference',
        'PubMed Central — millions of free full-text biomedical research articles (searchable directly through ANYFREEBOOK)',
        'Internet Archive\'s lending library — borrowable digital copies of many classic medical texts',
        'WHO and CDC publications — free, authoritative clinical guidelines and epidemiology references',
      ] },
      { type: 'h2', text: 'What to use for each preclinical subject' },
      { type: 'book', title: 'Anatomy & Physiology (OpenStax)', author: 'Rice University', note: 'Covers the standard two-semester A&P sequence. Not Gray\'s Anatomy — but for coursework, it\'s complete and free.' },
      { type: 'book', title: 'StatPearls', author: 'NCBI Bookshelf', note: 'Thousands of free, constantly updated clinical review articles. Widely used for board prep — think of it as a free reference shelf.' },
      { type: 'book', title: 'Gray\'s Anatomy (1918 edition)', author: 'Henry Gray', note: 'The classic edition is public domain on Project Gutenberg and Internet Archive. Anatomical fundamentals haven\'t changed; terminology sometimes has — use it alongside a modern atlas.' },
      { type: 'h2', text: 'A word of caution' },
      { type: 'p', text: 'Sites offering free downloads of current copyrighted editions (the newest Robbins, Katzung, or Harrison\'s) are piracy sites — they carry malware risk and legal risk, and we don\'t index them. The legal ecosystem above genuinely covers preclinical coursework; where it can\'t replace a current clinical text, your institution\'s library almost always provides electronic access for enrolled students — ask, because most students never do.' },
      { type: 'tip', text: 'ANYFREEBOOK searches PubMed Central, Internet Archive, and Open Library simultaneously — one search across the whole legal free-medical ecosystem.' },
    ],
  },
  {
    slug: '15-best-free-audiobooks-all-time',
    title: 'The 15 Best Free Audiobooks of All Time',
    description: 'The best legally free audiobooks — public domain classics with outstanding narrations, and where to listen to them.',
    category: 'Collections',
    readTime: '7 min',
    date: 'Dec 20, 2025',
    content: [
      { type: 'p', text: 'Audible costs $14.95 a month. But the public domain contains many of the greatest books ever written, and volunteer and archival projects have recorded them all. Here are fifteen that are genuinely excellent as listening experiences, not just famous titles.' },
      { type: 'h2', text: 'Fiction that works brilliantly as audio' },
      { type: 'ul', items: [
        'Pride and Prejudice (Jane Austen) — dialogue-driven and witty; Austen was practically writing for audio',
        'The Adventures of Sherlock Holmes (Arthur Conan Doyle) — short, self-contained mysteries, perfect for commutes',
        'Dracula (Bram Stoker) — written as letters and diary entries, so multi-reader recordings feel like radio drama',
        'The Count of Monte Cristo (Alexandre Dumas) — the greatest revenge plot ever, and long enough to last months',
        'Frankenstein (Mary Shelley) — short, atmospheric, and far better than any film version',
        'Treasure Island (Robert Louis Stevenson) — the ideal family listen',
        'A Christmas Carol (Charles Dickens) — Dickens performed it aloud himself on tour; it was built for the ear',
      ] },
      { type: 'h2', text: 'Nonfiction and ideas' },
      { type: 'ul', items: [
        'Meditations (Marcus Aurelius) — short, calming, and endlessly re-listenable',
        'The Art of War (Sun Tzu) — under two hours; the most quoted strategy text in history',
        'Walden (Henry David Thoreau) — slow listening in the best sense',
        'The Autobiography of Benjamin Franklin — surprisingly funny and modern',
        'On the Origin of Species (Charles Darwin) — clearer aloud than on the page',
      ] },
      { type: 'h2', text: 'Where the free recordings live' },
      { type: 'p', text: 'LibriVox coordinates volunteers who have recorded tens of thousands of public domain books — quality varies by narrator, so sample the first chapter and switch versions freely; popular titles have several. Internet Archive hosts and streams these plus archival recordings. ANYFREEBOOK\'s audiobooks section links directly to the source recordings, and the built-in reader can also read any public domain text aloud with text-to-speech.' },
      { type: 'tip', text: 'For multi-narrator LibriVox recordings, check the "dramatic reading" versions — Dracula and A Christmas Carol both have excellent ones.' },
    ],
  },
  {
    slug: 'free-alternatives-mankiw-economics',
    title: "Free Alternatives to Mankiw's Principles of Economics (Save $170)",
    description: "Mankiw's Principles of Economics costs about $170. These free, openly licensed alternatives teach the same intro micro and macro — used at real universities.",
    category: 'Economics',
    readTime: '8 min',
    date: 'Dec 15, 2025',
    content: [
      { type: 'p', text: 'Mankiw\'s Principles of Economics is the best-selling economics textbook in the world, and it costs about $170 new. Intro economics, however, is one of the best-covered subjects in open publishing — several complete, peer-reviewed, free textbooks teach the same ten principles, supply and demand, elasticity, market structures, and macro fundamentals.' },
      { type: 'h2', text: 'The direct replacements' },
      { type: 'book', title: 'Principles of Economics 3e (OpenStax)', author: 'Rice University', note: 'A complete micro + macro intro text, free as PDF or web. Chapter coverage maps closely to Mankiw — this is the default choice.' },
      { type: 'book', title: 'The Economy (CORE Econ)', author: 'CORE Team', note: 'A genuinely modern free textbook built by an international consortium — teaches economics through real data, inequality, and climate questions. Used at UCL and dozens of universities. Choose this if Mankiw bores you.' },
      { type: 'book', title: 'Principles of Microeconomics / Macroeconomics (OpenStax)', author: 'Rice University', note: 'The same OpenStax material split into single-semester volumes, matching how most courses are structured.' },
      { type: 'h2', text: 'Classic texts worth reading alongside' },
      { type: 'ul', items: [
        'The Wealth of Nations (Adam Smith) — public domain; read selectively, Book I especially',
        'Essays in Persuasion (John Maynard Keynes) — public domain in many countries; Keynes was a superb writer',
        'Economic Sophisms (Frédéric Bastiat) — free, short, and the wittiest defense of free trade ever written',
      ] },
      { type: 'h2', text: 'Making a free text work for a Mankiw course' },
      { type: 'p', text: 'Match by topic, not chapter number. Every intro course covers the same sequence: scarcity and trade-offs, supply and demand, elasticity, consumer/producer surplus, market failures, then GDP, inflation, unemployment, and monetary policy. OpenStax covers each with the same graphs. The end-of-chapter problems differ from your problem sets, but the concepts tested are identical — and CORE\'s interactive charts often explain them better than static textbook figures.' },
      { type: 'tip', text: 'Search "OpenStax economics" or any classic title on ANYFREEBOOK to jump straight to the legitimate free source.' },
    ],
  },
  {
    slug: 'free-books-yoruba-igbo-hausa',
    title: 'Free Books in Yoruba, Igbo, and Hausa: Where to Actually Find Them',
    description: 'Finding free books written originally in Yoruba, Igbo, or Hausa is harder than it should be. Here is what actually exists in the public domain and open archives, and how to search for it.',
    category: 'Languages',
    readTime: '8 min',
    date: 'Feb 2, 2026',
    content: [
      { type: 'p', text: "If you've tried to search \"free Yoruba books\" or \"free Igbo novels\" online, you already know the problem: most results are either English-language books about Nigeria, language-learning apps, or dead links. Original literature written in Nigeria's three major languages does exist online — it's just scattered across university digitization projects, national archives, and niche repositories that don't rank well in general search." },
      { type: 'h2', text: 'What actually exists — and why it\'s scattered' },
      { type: 'p', text: 'Early 20th-century literature in Yoruba, Igbo, and Hausa was often commissioned or published through colonial-era literacy bureaus, which means a real body of foundational work exists — but it was printed in small runs decades before digitization was a priority. Some of it has since been scanned by university libraries and archives; a lot hasn\'t.' },
      { type: 'book', title: 'Ogboju Ọdẹ Nínú Igbó Irúnmalẹ̀', author: 'D. O. Fagunwa', note: 'Widely considered the foundational Yoruba novel (1938), blending Yoruba folklore with a hunter\'s adventure narrative. Look for digitized editions and the English translation by Wole Soyinka, "The Forest of a Thousand Daemons," which is easier to find in library archives.' },
      { type: 'book', title: 'Omenuko', author: 'Pita Nwana', note: 'One of the earliest published Igbo-language novels (1933), based on the life of a real 19th-century Igbo trader. A landmark text for Igbo literature, worth searching university archive catalogs for.' },
      { type: 'book', title: 'Ruwan Bagaja', author: 'Abubakar Imam', note: 'A foundational Hausa novel (1934) that remains widely studied in West African literature courses. Search Hausa-language archive collections and Nigerian university digital libraries.' },
      { type: 'h2', text: 'How to search effectively' },
      { type: 'ul', items: [
        'Search the language name plus "language literature" rather than just the language — general search engines otherwise surface language-learning content.',
        'University special collections (especially University of Ibadan, Ahmadu Bello University, and University of Nigeria Nsukka) hold digitized colonial-era literature that general search engines rarely index well.',
        'Open Library and Internet Archive both let you filter search results by language — use the ISO code (yo, ig, ha) alongside the title if you know it.',
        'ANYFREEBOOK\'s dedicated Books in Yoruba, Books in Igbo, and Books in Hausa categories pull live results from these open archives in one place, updated automatically as new scans are added.',
      ] },
      { type: 'tip', text: 'If a specific out-of-print title isn\'t digitized anywhere yet, that\'s a real gap — not a sign it doesn\'t exist. Public and university libraries in Nigeria are still an important resource that hasn\'t been fully digitized.' },
    ],
  },
  {
    slug: 'best-free-nigerian-literature',
    title: 'The Best Free Nigerian Literature You Can Read Right Now',
    description: 'Public-domain and open-access Nigerian literature — novels, essays, and early works you can legally read for free, from foundational texts to lesser-known gems.',
    category: 'African Literature',
    readTime: '9 min',
    date: 'Feb 4, 2026',
    content: [
      { type: 'p', text: "Nigerian literature has one of the richest bodies of 20th-century writing in the world, but most readers only ever encounter the handful of titles assigned in school. A surprising amount of early Nigerian writing — much of it now in the public domain — is legally free to read if you know where to look." },
      { type: 'h2', text: 'Early foundational works' },
      { type: 'book', title: 'The Palm-Wine Drinkard', author: 'Amos Tutuola', note: 'Published in 1952, this was one of the first African novels to gain wide international attention — a surreal, folklore-infused journey narrated in a deliberately unconventional English. Check public domain and archive status by publication territory before assuming free availability, as copyright terms vary by country.' },
      { type: 'book', title: 'Ogboju Ọdẹ Nínú Igbó Irúnmalẹ̀ (The Forest of a Thousand Daemons)', author: 'D. O. Fagunwa, translated by Wole Soyinka', note: 'A landmark of Yoruba storytelling in English translation — mythic, episodic, and unlike most Western fantasy in structure.' },
      { type: 'h2', text: 'Essays, memoir, and nonfiction' },
      { type: 'p', text: "Nigerian nonfiction from the independence era is underrepresented in most \"free books\" lists, but it's some of the most historically important writing available — first-hand accounts of colonial rule ending and a new nation forming." },
      { type: 'ul', items: [
        'Search national archive digitization projects for independence-era pamphlets, speeches, and political essays — many are now public domain and hold up as genuinely good writing, not just historical artifacts.',
        'Colonial-era travel writing and ethnography by Nigerian authors is a lesser-known but real category worth searching, though read it with awareness of its historical framing.',
      ] },
      { type: 'h2', text: 'Where to search' },
      { type: 'p', text: 'ANYFREEBOOK\'s Nigerian Literature and African Literature categories aggregate live results from Open Library, Internet Archive, and Google Books, which is the most efficient starting point since availability shifts as more titles are digitized.' },
      { type: 'tip', text: 'Copyright status for African literature published between 1930–1980 varies significantly by country of first publication — a title being freely readable on one archive doesn\'t always mean it\'s public domain everywhere.' },
    ],
  },
  {
    slug: 'free-alternative-atkins-physical-chemistry',
    title: "Free Alternatives to Atkins' Physical Chemistry",
    description: "Atkins' Physical Chemistry is a standard but expensive textbook. Here are free, legal alternatives that cover the same core material for undergraduate physical chemistry.",
    category: 'Sciences',
    readTime: '7 min',
    date: 'Feb 6, 2026',
    content: [
      { type: 'p', text: "Atkins' Physical Chemistry is one of the most widely assigned textbooks in undergraduate chemistry, and new editions regularly run well over $150. The core subject — thermodynamics, quantum chemistry, kinetics, spectroscopy — is standard enough that several free, rigorous alternatives cover the same ground." },
      { type: 'h2', text: 'Free full courses and texts' },
      { type: 'book', title: 'Physical Chemistry (OpenStax / LibreTexts collections)', author: 'Multiple contributing authors', note: 'LibreTexts hosts an actively maintained, free, peer-reviewed physical chemistry textbook collection covering thermodynamics, quantum mechanics, and kinetics at the same depth as standard commercial texts.' },
      { type: 'book', title: '5.61 Physical Chemistry (MIT OpenCourseWare)', author: 'MIT Department of Chemistry', note: 'Full lecture notes, problem sets, and exams from MIT\'s undergraduate physical chemistry sequence, free and complete.' },
      { type: 'h2', text: 'Filling in specific topics' },
      { type: 'ul', items: [
        'Thermodynamics: search for free thermodynamics texts from MIT OCW or LibreTexts — the derivations match what Atkins covers chapter-for-chapter.',
        'Quantum chemistry: MIT\'s 5.61 and 5.73 courses cover this in more mathematical depth than most undergraduate texts, useful if Atkins feels too brief.',
        'Spectroscopy: search open-access spectroscopy course notes from any research university chemistry department — these are commonly published openly since the content changes little year to year.',
      ] },
      { type: 'tip', text: 'Physical chemistry problem sets are where courses actually differ most — pair a free textbook for concepts with your assigned course\'s specific problem sets rather than trying to match both exactly.' },
    ],
  },
  {
    slug: 'author-payout-models-explained',
    title: 'How Author Payout Models Actually Work: An Honest Comparison',
    description: 'Royalty percentages, ad-revenue sharing, reader-engagement payouts — a plain-language look at how different self-publishing and creator platforms actually pay authors.',
    category: 'For Authors',
    readTime: '9 min',
    date: 'Feb 8, 2026',
    content: [
      { type: 'p', text: "Every self-publishing platform advertises its payout terms differently, which makes them hard to compare. Some quote a royalty percentage of sale price. Some pay per page read. Some share ad revenue. This is a plain look at how the major models actually work, without picking a side." },
      { type: 'h2', text: 'Per-sale royalty models' },
      { type: 'p', text: 'The traditional model: a fixed percentage of each sale, typically 35–70% depending on price tier and exclusivity terms. The advantage is predictability — you know exactly what a sale is worth. The disadvantage is that it only pays when someone completes a purchase decision, and price competition in a crowded market pushes prices (and therefore per-sale earnings) down over time.' },
      { type: 'h2', text: 'Pages-read / engagement models' },
      { type: 'p', text: 'Some platforms pay from a shared fund divided by total pages read across all participating books that month. This rewards books that keep readers engaged all the way through, rather than just books that get purchased and abandoned. The tradeoff: your payout per page depends on how many other authors are also being read that month, which authors can\'t control or predict in advance.' },
      { type: 'h2', text: 'Ad-revenue sharing models' },
      { type: 'p', text: 'A smaller number of platforms — ANYFREEBOOK among them — remove the purchase decision entirely: readers access work for free, and a share of platform ad revenue (in ANYFREEBOOK\'s case, 40%) is distributed to authors based on verified reading engagement. This trades the ceiling of a per-copy sale for a much larger pool of potential readers, since there\'s no price barrier to someone starting your book.' },
      { type: 'ul', items: [
        'Per-sale royalty: higher ceiling per reader, but a real barrier — someone has to decide to pay before they ever read a word.',
        'Pages-read funds: rewards genuinely engaging books, but payout per page varies month to month.',
        'Ad-revenue sharing: removes the purchase barrier entirely, trades per-reader ceiling for reach.',
      ] },
      { type: 'tip', text: 'None of these models is objectively "better" — they optimize for different things. An author writing genre fiction for a broad audience and an author writing a niche technical guide will often see very different results from the same model.' },
    ],
  },
  {
    slug: 'public-domain-classics-reading-list',
    title: '20 Public Domain Classics Everyone Should Read for Free',
    description: 'A reading list of genuinely great public-domain novels — no filler, no obscure padding, just the classics that earned their reputation and cost nothing to read legally.',
    category: 'Literature',
    readTime: '10 min',
    date: 'Feb 10, 2026',
    content: [
      { type: 'p', text: 'Public domain lists often pad themselves with obscure Victorian novels nobody actually enjoys just to hit a round number. This list skips that — these are books that are genuinely worth reading, that also happen to be completely free because their copyright has expired.' },
      { type: 'h2', text: 'Where to start if you\'ve never read a "classic" for fun' },
      { type: 'book', title: 'Pride and Prejudice', author: 'Jane Austen', note: 'Sharper and funnier than its reputation as "serious literature" suggests — Austen\'s dialogue holds up better than most 21st-century sitcoms.' },
      { type: 'book', title: 'The Adventures of Sherlock Holmes', author: 'Arthur Conan Doyle', note: 'Short stories, not a novel — easy to read one at a time. Still the template every detective story since has borrowed from.' },
      { type: 'h2', text: 'For readers who want something denser' },
      { type: 'book', title: 'Crime and Punishment', author: 'Fyodor Dostoevsky', note: 'A genuine psychological thriller disguised as 19th-century Russian literature. Longer commitment, worth it.' },
      { type: 'book', title: 'Frankenstein', author: 'Mary Shelley', note: 'Wildly different from every film adaptation — the creature is articulate and the moral questions are far more uncomfortable than the pop-culture version suggests.' },
      { type: 'h2', text: 'Short and underrated' },
      { type: 'book', title: 'The Yellow Wallpaper', author: 'Charlotte Perkins Gilman', note: 'A short story, readable in one sitting, and one of the sharpest critiques of 19th-century medicine ever written.' },
      { type: 'book', title: 'Heart of Darkness', author: 'Joseph Conrad', note: 'Short, dense, and the direct inspiration for Apocalypse Now — worth reading with awareness of its colonial-era framing.' },
      { type: 'tip', text: 'Public domain status depends on the author\'s death date and varies by country — most pre-1928 English-language works are safely public domain in the US, but always check local copyright term if you\'re outside the US.' },
    ],
  },
  {
    slug: 'free-poetry-collections-worth-reading',
    title: 'Free Poetry Collections Actually Worth Reading Online',
    description: 'Skip the random single-poem blog posts — full public-domain poetry collections, from accessible to challenging, that are free to read in their entirety.',
    category: 'Poetry',
    readTime: '6 min',
    date: 'Feb 12, 2026',
    content: [
      { type: 'p', text: 'Most "free poetry" search results are single poems scattered across quote-aggregator sites with no context. Full collections, read as their poets intended, are a different experience — here are ones worth reading start to finish.' },
      { type: 'book', title: 'Leaves of Grass', author: 'Walt Whitman', note: 'Whitman revised this collection across his entire life — later editions are richer, but the original 1855 edition has a raw energy the later versions smooth over.' },
      { type: 'book', title: 'The Complete Poems of Emily Dickinson', author: 'Emily Dickinson', note: 'Best read in short sessions, not all at once — the poems are dense and reward slow reading over a marathon.' },
      { type: 'book', title: 'Sonnets from the Portuguese', author: 'Elizabeth Barrett Browning', note: 'A tightly focused sonnet sequence about falling in love — much shorter and more accessible than most 19th-century poetry.' },
      { type: 'h2', text: 'For a different tradition' },
      { type: 'p', text: 'Public domain poetry in translation opens up entirely different traditions — classical Persian, Chinese, and Japanese poetry all have public-domain English translations worth seeking out, though translation quality varies significantly between editions, so it\'s worth comparing more than one if a particular poem matters to you.' },
      { type: 'tip', text: 'ANYFREEBOOK\'s Poetry & Rhymes category pulls live results across these and many more collections in one search.' },
    ],
  },
  {
    slug: 'free-waec-jamb-study-resources',
    title: 'Free Study Resources for WAEC and JAMB Preparation',
    description: 'A practical guide to legitimate free study materials for WAEC and JAMB exam preparation — past questions, syllabus-aligned texts, and how to structure a study plan.',
    category: 'Education',
    readTime: '8 min',
    date: 'Feb 14, 2026',
    content: [
      { type: 'p', text: 'WAEC and JAMB preparation materials are sold aggressively, but a genuine amount of useful, syllabus-aligned free material exists if you know how to filter it from low-quality copies.' },
      { type: 'h2', text: 'What actually helps' },
      { type: 'ul', items: [
        'Past questions matter more than any single textbook — pattern familiarity is most of the exam-readiness battle for both WAEC and JAMB.',
        'The official syllabus documents (published by WAEC and JAMB directly) are free and specify exactly what\'s examinable — starting a study plan from an unofficial guide instead of the syllabus wastes time on material that isn\'t tested.',
        'Free OpenStax and open-access textbooks cover most core subjects (biology, chemistry, physics, economics, government) at a level that maps closely onto WAEC/JAMB syllabus requirements, even though they weren\'t written specifically for these exams.',
      ] },
      { type: 'h2', text: 'Structuring a study plan' },
      { type: 'p', text: 'Work backward from the exam date: allocate the first half of your remaining time to working through syllabus topics you haven\'t covered, and the second half almost entirely to past questions under timed conditions. Most students over-invest in reading and under-invest in timed practice, which is the actual skill being tested.' },
      { type: 'tip', text: 'ANYFREEBOOK\'s WAEC & JAMB resources page collects curated official and open-access study material in one place, updated as new resources become available.' },
    ],
  },
  {
    slug: 'free-french-literature-original-and-translation',
    title: 'Free French Literature: Reading in the Original vs. Translation',
    description: 'Where to find classic French literature free online, and an honest look at when reading in the original is worth the effort versus reading a good translation.',
    category: 'Languages',
    readTime: '7 min',
    date: 'Feb 16, 2026',
    content: [
      { type: 'p', text: 'French literature has an unusually large public-domain catalog because copyright terms have expired on most major 19th-century work, and French digitization projects (particularly Gallica, the French national library\'s archive) are extensive. The real question for most readers isn\'t availability — it\'s whether to read in French or translation.' },
      { type: 'h2', text: 'Free in the original French' },
      { type: 'book', title: 'Le Comte de Monte-Cristo', author: 'Alexandre Dumas', note: 'Long, but Dumas writes in genuinely accessible French — a reasonable choice for intermediate French readers wanting to try a full novel.' },
      { type: 'book', title: 'Madame Bovary', author: 'Gustave Flaubert', note: 'Denser prose than Dumas — better attempted after some experience reading French novels, not as a first attempt.' },
      { type: 'h2', text: 'When translation is the better choice' },
      { type: 'p', text: 'Poetry and wordplay-heavy prose lose the most in translation — but if your French isn\'t at a level where you can read fluently without constant dictionary lookups, a good translation will get you the actual story and ideas faster than a frustrating slog through the original. Read translated first, original later once you\'re more comfortable, rather than forcing the original as a beginner.' },
      { type: 'tip', text: 'ANYFREEBOOK\'s Books in French and French Literature categories both surface live results — the first for French-language originals, the second includes English translations as well.' },
    ],
  },
  {
    slug: 'how-to-host-free-live-online-class',
    title: 'How to Host a Free Live Online Class: A Practical Guide',
    description: 'A step-by-step guide for educators and authors wanting to host live online classes without expensive video software or a technical setup.',
    category: 'Teaching',
    readTime: '7 min',
    date: 'Feb 18, 2026',
    content: [
      { type: 'p', text: "Hosting a live online class used to require either expensive webinar software or wrestling with video conferencing tools not built for teaching. Here's a practical walkthrough of what actually matters for a good live class, regardless of which platform you use." },
      { type: 'h2', text: 'Before you go live' },
      { type: 'ul', items: [
        'Test your camera and microphone a few minutes before start time, not the moment class begins — audio problems are the single most common thing that derails a live class.',
        'Have your material (slides, a document, or a book you\'re teaching from) ready to share before you start, not mid-class.',
        'Decide in advance whether your class is public (open to anyone who finds it) or private (invite-link only) — this changes how you should promote it.',
      ] },
      { type: 'h2', text: 'During the class' },
      { type: 'p', text: "Live chat is your most valuable tool for gauging whether people are following along — silence doesn't mean people are lost, but a complete absence of chat activity for a long stretch usually means it's worth pausing to check in directly." },
      { type: 'h2', text: 'Choosing a platform' },
      { type: 'p', text: 'Free platforms exist that don\'t require attendees to sign up for anything or download software — ANYFREEBOOK\'s classroom feature, for example, runs entirely in-browser for both host and viewers, with document sharing built in so you can teach directly from a book or set of notes without switching windows.' },
      { type: 'tip', text: 'Start small. A first live class with five real attendees who stay engaged is more valuable than a poorly-run session with fifty who leave halfway through.' },
    ],
  },
  {
    slug: 'free-philosophy-books-that-change-thinking',
    title: '15 Free Philosophy Books That Actually Change How You Think',
    description: 'Skip the intimidating survey textbooks — these free, public-domain philosophy books are genuinely readable and worth the time, from ancient to modern.',
    category: 'Philosophy',
    readTime: '9 min',
    date: 'Feb 20, 2026',
    content: [
      { type: 'p', text: 'Philosophy has a reputation for being inaccessible, and some of it deserves that reputation. But a real subset of foundational philosophy is genuinely readable without a background in the field — and almost all of it, being centuries old, is completely free.' },
      { type: 'h2', text: 'Ancient philosophy — surprisingly practical' },
      { type: 'book', title: 'Meditations', author: 'Marcus Aurelius', note: 'Written as private notes to himself, not for publication — reads more like a journal than a treatise, and is one of the most accessible entry points into Stoic philosophy.' },
      { type: 'book', title: 'The Enchiridion', author: 'Epictetus', note: 'Short, direct, practical — closer to a set of life rules than abstract philosophy.' },
      { type: 'h2', text: 'Modern philosophy that reads clearly' },
      { type: 'book', title: 'On Liberty', author: 'John Stuart Mill', note: 'Still one of the clearest, most directly argued defenses of individual freedom ever written — genuinely readable without prior philosophy background.' },
      { type: 'book', title: 'Beyond Good and Evil', author: 'Friedrich Nietzsche', note: 'Denser and more challenging than the others on this list, written in aphorisms rather than sustained argument — better as a second or third philosophy book, not a first.' },
      { type: 'h2', text: 'A practical way to start' },
      { type: 'p', text: 'Start with Meditations or The Enchiridion regardless of what draws you to philosophy generally — both are short, were never meant to be intimidating, and give you a real feel for philosophical thinking before you tackle anything longer.' },
      { type: 'tip', text: 'Read philosophy slower than fiction — a page of dense argument often needs re-reading, and that\'s normal, not a sign you\'re reading wrong.' },
    ],
  },
  {
    slug: 'free-business-startup-books-for-founders',
    title: 'Free Business and Startup Books Every First-Time Founder Should Read',
    description: 'Business bestsellers are expensive and often padded. Here are genuinely useful, freely available business and economics books for first-time founders.',
    category: 'Business',
    readTime: '8 min',
    date: 'Feb 22, 2026',
    content: [
      { type: 'p', text: "Most bestselling business books cost $20–30 and could be a long-form blog post. A smaller set of genuinely foundational business and economics writing is both more substantial and completely free, because it's old enough to be public domain or was released openly by its author or institution." },
      { type: 'h2', text: 'Foundational economics for founders' },
      { type: 'book', title: 'The Wealth of Nations', author: 'Adam Smith', note: 'Long, and you don\'t need all of it — Book I on the division of labor and markets is the most directly useful section for understanding how markets actually behave.' },
      { type: 'h2', text: 'Open, modern business resources' },
      { type: 'p', text: 'Several universities and business schools have released core strategy, marketing, and finance course material openly — MIT OpenCourseWare\'s Sloan School offerings in particular cover entrepreneurship and finance fundamentals at the same depth as paid MBA-adjacent courses.' },
      { type: 'ul', items: [
        'MIT OpenCourseWare\'s entrepreneurship and finance courses — free, complete, with problem sets.',
        'Open-access accounting fundamentals texts (search "principles of accounting open textbook") cover exactly what a first-time founder needs to read their own financial statements.',
        'Government small-business resources (in most countries) are free and often more directly applicable than general business bestsellers, since they\'re written for your specific regulatory environment.',
      ] },
      { type: 'h2', text: 'What to actually read first' },
      { type: 'p', text: "If you're pre-revenue, prioritize a free accounting fundamentals resource over strategy books — understanding your own numbers matters more at this stage than frameworks for decisions you're not ready to make yet." },
      { type: 'tip', text: 'ANYFREEBOOK\'s Business and Entrepreneurship categories aggregate current free titles across these areas, refreshed automatically.' },
    ],
  },
  {
    slug: 'free-engineering-textbooks-subject-guide',
    title: 'Free Engineering Textbooks: A Subject-by-Subject Guide',
    description: 'Engineering textbooks routinely cost $150–300. Here is where to find free, legitimate alternatives across mechanical, electrical, civil, and chemical engineering.',
    category: 'Engineering',
    readTime: '9 min',
    date: 'Feb 24, 2026',
    content: [
      { type: 'p', text: 'Engineering textbooks are some of the most expensive on any university book list, and new editions are released frequently enough that used copies don\'t stay cheap for long. The core material changes slowly, though, which means free alternatives stay usable for years.' },
      { type: 'h2', text: 'Mechanical engineering' },
      { type: 'p', text: 'MIT OpenCourseWare\'s mechanical engineering department has released full course material — lecture notes, problem sets, and often full video lectures — for statics, dynamics, thermodynamics, and materials science.' },
      { type: 'h2', text: 'Electrical engineering' },
      { type: 'book', title: 'Circuits and Electronics (MIT 6.002x course material)', author: 'MIT Department of EECS', note: 'Complete free course material covering circuit analysis fundamentals, the same core content as most introductory circuits textbooks.' },
      { type: 'h2', text: 'Civil engineering' },
      { type: 'p', text: 'Structural analysis and statics fundamentals are well covered by MIT and other OpenCourseWare offerings — search by specific topic (structural analysis, soil mechanics, fluid mechanics) rather than a general "civil engineering textbook" search, since the material is usually organized by course, not as a single omnibus text.' },
      { type: 'h2', text: 'Chemical engineering' },
      { type: 'ul', items: [
        'Search "chemical engineering thermodynamics open textbook" for free alternatives covering the same material as standard commercial texts.',
        'Process design and unit operations fundamentals are covered in several openly licensed university course packets, worth searching by specific topic.',
      ] },
      { type: 'tip', text: 'Engineering fundamentals (statics, thermodynamics, circuit theory) change far less between editions than the marketing suggests — a free text from a few years ago is almost always still fully usable for coursework.' },
    ],
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find(p => p.slug === slug);
}
