export interface BlogBlock {
  type: 'p' | 'h2' | 'ul' | 'book' | 'tip';
  text?: string;
  items?: string[];
  title?: string;
  author?: string;
  note?: string;
}

export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  category: string;
  readTime: string;
  date: string;
  content: BlogBlock[];
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: 'top-25-free-programming-books-2026',
    title: 'Top 25 Free Programming Books in 2026',
    description: 'The best free programming books for every language and skill level — from Python beginners to systems programming, all legally free to read and download.',
    category: 'Technology',
    readTime: '12 min',
    date: 'Jan 15, 2026',
    content: [
      { type: 'p', text: 'Programming books are expensive — a single new O\'Reilly title often costs $40–60, and a full learning path can run past $300. The good news: some of the most respected programming books ever written are completely free, released by their authors under open licenses or published openly on the web. This list collects 25 of the best, organized by where you are in your journey.' },
      { type: 'h2', text: 'For complete beginners' },
      { type: 'book', title: 'Automate the Boring Stuff with Python', author: 'Al Sweigart', note: 'The single best first programming book. Free to read online, teaches Python through practical tasks — renaming files, filling forms, scraping websites — instead of abstract theory.' },
      { type: 'book', title: 'Python Crash Course', author: 'Eric Matthes', note: 'A structured, project-driven introduction. Pairs well with Automate the Boring Stuff: read this for foundations, that for practical wins.' },
      { type: 'book', title: 'Eloquent JavaScript', author: 'Marijn Haverbeke', note: 'The classic free introduction to JavaScript and programming in general, with interactive exercises built into the online edition.' },
      { type: 'p', text: 'Start with exactly one of these, finish it, and build something small before adding more books. Collecting books is not the same as learning.' },
      { type: 'h2', text: 'Leveling up: intermediate essentials' },
      { type: 'book', title: 'You Don\'t Know JS', author: 'Kyle Simpson', note: 'A free book series that goes deep on how JavaScript actually works — scope, closures, prototypes, async. Read after your first project, not before.' },
      { type: 'book', title: 'The Linux Command Line', author: 'William Shotts', note: 'Free from the author. Every developer eventually needs the terminal; this is the gentlest thorough introduction.' },
      { type: 'book', title: 'Pro Git', author: 'Scott Chacon & Ben Straub', note: 'The official Git book, free forever. Chapters 1–3 cover 90% of what you\'ll use daily.' },
      { type: 'book', title: 'Structure and Interpretation of Computer Programs', author: 'Abelson & Sussman', note: 'MIT\'s legendary text, free online. Harder than everything above, and worth it — it changes how you think about programs.' },
      { type: 'h2', text: 'Specialization: data, ML, and systems' },
      { type: 'book', title: 'Deep Learning', author: 'Ian Goodfellow, Yoshua Bengio & Aaron Courville', note: 'The standard deep learning reference, free on the authors\' site. Requires linear algebra and calculus.' },
      { type: 'book', title: 'The TypeScript Handbook', author: 'Microsoft', note: 'The official, always-current way to learn TypeScript, maintained free by the language team itself.' },
      { type: 'ul', items: [
        'Operating Systems: Three Easy Pieces — the free OS textbook used by dozens of universities',
        'High Performance Browser Networking (Ilya Grigorik) — free from O\'Reilly, essential for web performance',
        'The Rust Book — the official free way to learn Rust',
        'Dive Into Deep Learning — free, code-first ML with runnable notebooks',
        'Crafting Interpreters (Robert Nystrom) — free online; build two programming languages from scratch',
      ] },
      { type: 'h2', text: 'How to actually find these' },
      { type: 'p', text: 'Every book above is searchable on ANYFREEBOOK — we aggregate Open Library, Project Gutenberg, Internet Archive, Google Books, and open-access repositories in one search. Type the title, check the source badge, and read online or download in the formats the source offers. No sign-up needed.' },
      { type: 'tip', text: 'Pick one book. Finish it. Build a small project with what you learned. Then come back for the next one — that loop beats any 25-book reading marathon.' },
    ],
  },
  {
    slug: 'free-alternatives-campbell-biology',
    title: 'Free Alternatives to Campbell Biology (Save $189)',
    description: 'Campbell Biology costs $189 new. These free, legal alternatives cover the same introductory biology material — used by real universities.',
    category: 'Sciences',
    readTime: '8 min',
    date: 'Jan 10, 2026',
    content: [
      { type: 'p', text: 'Campbell Biology is the standard first-year biology text at hundreds of universities, and a new copy costs about $189 — more than many students\' weekly budget. If your course follows the standard intro-biology sequence (cell biology, genetics, evolution, physiology, ecology), openly licensed textbooks cover the same ground for free.' },
      { type: 'h2', text: 'The best free replacement' },
      { type: 'book', title: 'Biology 2e (OpenStax)', author: 'Rice University', note: 'A complete, peer-reviewed intro biology textbook written specifically to match courses that use Campbell. Free PDF and web versions, professionally edited, with review questions per chapter. This is the one to get.' },
      { type: 'p', text: 'OpenStax is published by Rice University and funded by foundations precisely so students don\'t have to buy $200 textbooks. Their books are not scans or summaries — they are complete textbooks used officially at thousands of institutions.' },
      { type: 'h2', text: 'Free books for specific units' },
      { type: 'ul', items: [
        'Concepts of Biology (OpenStax) — a lighter one-semester version for non-majors',
        'Microbiology (OpenStax) — if your course leans micro',
        'Anatomy and Physiology (OpenStax) — for the physiology units',
        'On the Origin of Species (Darwin) — public domain on Project Gutenberg; still remarkably readable for the evolution unit',
      ] },
      { type: 'h2', text: 'How to study from a free textbook when your class uses Campbell' },
      { type: 'p', text: 'Chapter numbers won\'t match, so navigate by topic instead: your syllabus says "cell respiration," you read the cell respiration chapter. Free texts include the same figures-first explanations, and end-of-chapter questions map closely. For the handful of topics where your professor references specific Campbell figures, a library reserve copy fills the gap — most university libraries keep one.' },
      { type: 'tip', text: 'Search any of these titles on ANYFREEBOOK to get the direct source link — we aggregate OpenStax mirrors, Internet Archive, and Open Library in one search.' },
    ],
  },
  {
    slug: 'learn-machine-learning-free-reading-list',
    title: 'Learn Machine Learning for Free — Complete Reading List',
    description: 'A free, ordered reading path from ML beginner to practitioner: 15 books with estimated study times, all legally free.',
    category: 'Technology',
    readTime: '10 min',
    date: 'Jan 5, 2026',
    content: [
      { type: 'p', text: 'Machine learning has the best free literature of any technical field — the standard references are free because the researchers who wrote them wanted them read. The problem isn\'t finding free ML books; it\'s reading them in an order that doesn\'t crush you. Here\'s a path that works, with honest time estimates.' },
      { type: 'h2', text: 'Stage 1: Foundations (4–8 weeks)' },
      { type: 'book', title: 'Python Crash Course', author: 'Eric Matthes', note: 'Skip if you already write Python comfortably. Otherwise, everything downstream depends on this.' },
      { type: 'book', title: 'Mathematics for Machine Learning', author: 'Deisenroth, Faisal & Ong', note: 'Free from Cambridge University Press. Linear algebra, calculus, and probability — exactly the subset ML needs, no more.' },
      { type: 'h2', text: 'Stage 2: Core ML (6–10 weeks)' },
      { type: 'book', title: 'An Introduction to Statistical Learning', author: 'James, Witten, Hastie & Tibshirani', note: 'The most recommended first ML book on earth, free from the authors. Concepts first, math second, with labs in Python or R.' },
      { type: 'book', title: 'Dive Into Deep Learning', author: 'Zhang, Lipton, Li & Smola', note: 'Free and interactive — every concept comes with runnable code. The fastest route from "I know Python" to "I trained a network."' },
      { type: 'h2', text: 'Stage 3: Depth (ongoing)' },
      { type: 'book', title: 'Deep Learning', author: 'Goodfellow, Bengio & Courville', note: 'The reference text, free online. Read chapters as you need them rather than front to back.' },
      { type: 'book', title: 'The Elements of Statistical Learning', author: 'Hastie, Tibshirani & Friedman', note: 'The heavyweight older sibling of ISL, also free. Graduate level; treat it as an encyclopedia.' },
      { type: 'ul', items: [
        'Pattern Recognition and Machine Learning (Bishop) — free PDF released by Microsoft Research',
        'Reinforcement Learning: An Introduction (Sutton & Barto) — the standard RL text, free from the authors',
        'Speech and Language Processing (Jurafsky & Martin) — free drafts; the NLP standard',
        'Probabilistic Machine Learning (Murphy) — modern, comprehensive, free drafts online',
      ] },
      { type: 'h2', text: 'The honest advice' },
      { type: 'p', text: 'Most people fail this path by reading Stage 3 books first. ISL plus Dive Into Deep Learning, actually completed with the exercises, puts you ahead of the majority of self-taught ML learners. Total cost of the entire path above: $0.' },
      { type: 'tip', text: 'All of these are findable through ANYFREEBOOK search — we link you to the official free versions hosted by the authors and open repositories.' },
    ],
  },
  {
    slug: 'where-to-download-free-medical-textbooks',
    title: 'Where to Download Free Medical Textbooks Online',
    description: 'A complete guide to finding free, legal medical textbooks and references: anatomy, pharmacology, pathology, and the open-access sources that host them.',
    category: 'Medicine',
    readTime: '9 min',
    date: 'Dec 28, 2025',
    content: [
      { type: 'p', text: 'Medical textbooks are the most expensive books in education — $100–350 each, with a preclinical shelf easily passing $1,500. There is a real, legal free ecosystem, but you need to know which sources are legitimate. Everything below is legal and openly licensed or public access.' },
      { type: 'h2', text: 'The legitimate free sources' },
      { type: 'ul', items: [
        'OpenStax Anatomy & Physiology — a complete, peer-reviewed A&P textbook, free from Rice University',
        'NCBI Bookshelf — the U.S. National Library of Medicine hosts full free books including StatPearls, essentially a free encyclopedic clinical reference',
        'PubMed Central — millions of free full-text biomedical research articles (searchable directly through ANYFREEBOOK)',
        'Internet Archive\'s lending library — borrowable digital copies of many classic medical texts',
        'WHO and CDC publications — free, authoritative clinical guidelines and epidemiology references',
      ] },
      { type: 'h2', text: 'What to use for each preclinical subject' },
      { type: 'book', title: 'Anatomy & Physiology (OpenStax)', author: 'Rice University', note: 'Covers the standard two-semester A&P sequence. Not Gray\'s Anatomy — but for coursework, it\'s complete and free.' },
      { type: 'book', title: 'StatPearls', author: 'NCBI Bookshelf', note: 'Thousands of free, constantly updated clinical review articles. Widely used for board prep — think of it as a free reference shelf.' },
      { type: 'book', title: 'Gray\'s Anatomy (1918 edition)', author: 'Henry Gray', note: 'The classic edition is public domain on Project Gutenberg and Internet Archive. Anatomical fundamentals haven\'t changed; terminology sometimes has — use it alongside a modern atlas.' },
      { type: 'h2', text: 'A word of caution' },
      { type: 'p', text: 'Sites offering free downloads of current copyrighted editions (the newest Robbins, Katzung, or Harrison\'s) are piracy sites — they carry malware risk and legal risk, and we don\'t index them. The legal ecosystem above genuinely covers preclinical coursework; where it can\'t replace a current clinical text, your institution\'s library almost always provides electronic access for enrolled students — ask, because most students never do.' },
      { type: 'tip', text: 'ANYFREEBOOK searches PubMed Central, Internet Archive, and Open Library simultaneously — one search across the whole legal free-medical ecosystem.' },
    ],
  },
  {
    slug: '15-best-free-audiobooks-all-time',
    title: 'The 15 Best Free Audiobooks of All Time',
    description: 'The best legally free audiobooks — public domain classics with outstanding narrations, and where to listen to them.',
    category: 'Collections',
    readTime: '7 min',
    date: 'Dec 20, 2025',
    content: [
      { type: 'p', text: 'Audible costs $14.95 a month. But the public domain contains many of the greatest books ever written, and volunteer and archival projects have recorded them all. Here are fifteen that are genuinely excellent as listening experiences, not just famous titles.' },
      { type: 'h2', text: 'Fiction that works brilliantly as audio' },
      { type: 'ul', items: [
        'Pride and Prejudice (Jane Austen) — dialogue-driven and witty; Austen was practically writing for audio',
        'The Adventures of Sherlock Holmes (Arthur Conan Doyle) — short, self-contained mysteries, perfect for commutes',
        'Dracula (Bram Stoker) — written as letters and diary entries, so multi-reader recordings feel like radio drama',
        'The Count of Monte Cristo (Alexandre Dumas) — the greatest revenge plot ever, and long enough to last months',
        'Frankenstein (Mary Shelley) — short, atmospheric, and far better than any film version',
        'Treasure Island (Robert Louis Stevenson) — the ideal family listen',
        'A Christmas Carol (Charles Dickens) — Dickens performed it aloud himself on tour; it was built for the ear',
      ] },
      { type: 'h2', text: 'Nonfiction and ideas' },
      { type: 'ul', items: [
        'Meditations (Marcus Aurelius) — short, calming, and endlessly re-listenable',
        'The Art of War (Sun Tzu) — under two hours; the most quoted strategy text in history',
        'Walden (Henry David Thoreau) — slow listening in the best sense',
        'The Autobiography of Benjamin Franklin — surprisingly funny and modern',
        'On the Origin of Species (Charles Darwin) — clearer aloud than on the page',
      ] },
      { type: 'h2', text: 'Where the free recordings live' },
      { type: 'p', text: 'LibriVox coordinates volunteers who have recorded tens of thousands of public domain books — quality varies by narrator, so sample the first chapter and switch versions freely; popular titles have several. Internet Archive hosts and streams these plus archival recordings. ANYFREEBOOK\'s audiobooks section links directly to the source recordings, and the built-in reader can also read any public domain text aloud with text-to-speech.' },
      { type: 'tip', text: 'For multi-narrator LibriVox recordings, check the "dramatic reading" versions — Dracula and A Christmas Carol both have excellent ones.' },
    ],
  },
  {
    slug: 'free-alternatives-mankiw-economics',
    title: "Free Alternatives to Mankiw's Principles of Economics (Save $170)",
    description: "Mankiw's Principles of Economics costs about $170. These free, openly licensed alternatives teach the same intro micro and macro — used at real universities.",
    category: 'Economics',
    readTime: '8 min',
    date: 'Dec 15, 2025',
    content: [
      { type: 'p', text: 'Mankiw\'s Principles of Economics is the best-selling economics textbook in the world, and it costs about $170 new. Intro economics, however, is one of the best-covered subjects in open publishing — several complete, peer-reviewed, free textbooks teach the same ten principles, supply and demand, elasticity, market structures, and macro fundamentals.' },
      { type: 'h2', text: 'The direct replacements' },
      { type: 'book', title: 'Principles of Economics 3e (OpenStax)', author: 'Rice University', note: 'A complete micro + macro intro text, free as PDF or web. Chapter coverage maps closely to Mankiw — this is the default choice.' },
      { type: 'book', title: 'The Economy (CORE Econ)', author: 'CORE Team', note: 'A genuinely modern free textbook built by an international consortium — teaches economics through real data, inequality, and climate questions. Used at UCL and dozens of universities. Choose this if Mankiw bores you.' },
      { type: 'book', title: 'Principles of Microeconomics / Macroeconomics (OpenStax)', author: 'Rice University', note: 'The same OpenStax material split into single-semester volumes, matching how most courses are structured.' },
      { type: 'h2', text: 'Classic texts worth reading alongside' },
      { type: 'ul', items: [
        'The Wealth of Nations (Adam Smith) — public domain; read selectively, Book I especially',
        'Essays in Persuasion (John Maynard Keynes) — public domain in many countries; Keynes was a superb writer',
        'Economic Sophisms (Frédéric Bastiat) — free, short, and the wittiest defense of free trade ever written',
      ] },
      { type: 'h2', text: 'Making a free text work for a Mankiw course' },
      { type: 'p', text: 'Match by topic, not chapter number. Every intro course covers the same sequence: scarcity and trade-offs, supply and demand, elasticity, consumer/producer surplus, market failures, then GDP, inflation, unemployment, and monetary policy. OpenStax covers each with the same graphs. The end-of-chapter problems differ from your problem sets, but the concepts tested are identical — and CORE\'s interactive charts often explain them better than static textbook figures.' },
      { type: 'tip', text: 'Search "OpenStax economics" or any classic title on ANYFREEBOOK to jump straight to the legitimate free source.' },
    ],
  },
  {
    slug: 'free-books-yoruba-igbo-hausa',
    title: 'Free Books in Yoruba, Igbo, and Hausa: Where to Actually Find Them',
    description: 'Finding free books written originally in Yoruba, Igbo, or Hausa is harder than it should be. Here is what actually exists in the public domain and open archives, and how to search for it.',
    category: 'Languages',
    readTime: '8 min',
    date: 'Feb 2, 2026',
    content: [
      { type: 'p', text: "If you've tried to search \"free Yoruba books\" or \"free Igbo novels\" online, you already know the problem: most results are either English-language books about Nigeria, language-learning apps, or dead links. Original literature written in Nigeria's three major languages does exist online — it's just scattered across university digitization projects, national archives, and niche repositories that don't rank well in general search." },
      { type: 'h2', text: 'What actually exists — and why it\'s scattered' },
      { type: 'p', text: 'Early 20th-century literature in Yoruba, Igbo, and Hausa was often commissioned or published through colonial-era literacy bureaus, which means a real body of foundational work exists — but it was printed in small runs decades before digitization was a priority. Some of it has since been scanned by university libraries and archives; a lot hasn\'t.' },
      { type: 'book', title: 'Ogboju Ọdẹ Nínú Igbó Irúnmalẹ̀', author: 'D. O. Fagunwa', note: 'Widely considered the foundational Yoruba novel (1938), blending Yoruba folklore with a hunter\'s adventure narrative. Look for digitized editions and the English translation by Wole Soyinka, "The Forest of a Thousand Daemons," which is easier to find in library archives.' },
      { type: 'book', title: 'Omenuko', author: 'Pita Nwana', note: 'One of the earliest published Igbo-language novels (1933), based on the life of a real 19th-century Igbo trader. A landmark text for Igbo literature, worth searching university archive catalogs for.' },
      { type: 'book', title: 'Ruwan Bagaja', author: 'Abubakar Imam', note: 'A foundational Hausa novel (1934) that remains widely studied in West African literature courses. Search Hausa-language archive collections and Nigerian university digital libraries.' },
      { type: 'h2', text: 'How to search effectively' },
      { type: 'ul', items: [
        'Search the language name plus "language literature" rather than just the language — general search engines otherwise surface language-learning content.',
        'University special collections (especially University of Ibadan, Ahmadu Bello University, and University of Nigeria Nsukka) hold digitized colonial-era literature that general search engines rarely index well.',
        'Open Library and Internet Archive both let you filter search results by language — use the ISO code (yo, ig, ha) alongside the title if you know it.',
        'ANYFREEBOOK\'s dedicated Books in Yoruba, Books in Igbo, and Books in Hausa categories pull live results from these open archives in one place, updated automatically as new scans are added.',
      ] },
      { type: 'tip', text: 'If a specific out-of-print title isn\'t digitized anywhere yet, that\'s a real gap — not a sign it doesn\'t exist. Public and university libraries in Nigeria are still an important resource that hasn\'t been fully digitized.' },
    ],
  },
  {
    slug: 'best-free-nigerian-literature',
    title: 'The Best Free Nigerian Literature You Can Read Right Now',
    description: 'Public-domain and open-access Nigerian literature — novels, essays, and early works you can legally read for free, from foundational texts to lesser-known gems.',
    category: 'African Literature',
    readTime: '9 min',
    date: 'Feb 4, 2026',
    content: [
      { type: 'p', text: "Nigerian literature has one of the richest bodies of 20th-century writing in the world, but most readers only ever encounter the handful of titles assigned in school. A surprising amount of early Nigerian writing — much of it now in the public domain — is legally free to read if you know where to look." },
      { type: 'h2', text: 'Early foundational works' },
      { type: 'book', title: 'The Palm-Wine Drinkard', author: 'Amos Tutuola', note: 'Published in 1952, this was one of the first African novels to gain wide international attention — a surreal, folklore-infused journey narrated in a deliberately unconventional English. Check public domain and archive status by publication territory before assuming free availability, as copyright terms vary by country.' },
      { type: 'book', title: 'Ogboju Ọdẹ Nínú Igbó Irúnmalẹ̀ (The Forest of a Thousand Daemons)', author: 'D. O. Fagunwa, translated by Wole Soyinka', note: 'A landmark of Yoruba storytelling in English translation — mythic, episodic, and unlike most Western fantasy in structure.' },
      { type: 'h2', text: 'Essays, memoir, and nonfiction' },
      { type: 'p', text: "Nigerian nonfiction from the independence era is underrepresented in most \"free books\" lists, but it's some of the most historically important writing available — first-hand accounts of colonial rule ending and a new nation forming." },
      { type: 'ul', items: [
        'Search national archive digitization projects for independence-era pamphlets, speeches, and political essays — many are now public domain and hold up as genuinely good writing, not just historical artifacts.',
        'Colonial-era travel writing and ethnography by Nigerian authors is a lesser-known but real category worth searching, though read it with awareness of its historical framing.',
      ] },
      { type: 'h2', text: 'Where to search' },
      { type: 'p', text: 'ANYFREEBOOK\'s Nigerian Literature and African Literature categories aggregate live results from Open Library, Internet Archive, and Google Books, which is the most efficient starting point since availability shifts as more titles are digitized.' },
      { type: 'tip', text: 'Copyright status for African literature published between 1930–1980 varies significantly by country of first publication — a title being freely readable on one archive doesn\'t always mean it\'s public domain everywhere.' },
    ],
  },
  {
    slug: 'free-alternative-atkins-physical-chemistry',
    title: "Free Alternatives to Atkins' Physical Chemistry",
    description: "Atkins' Physical Chemistry is a standard but expensive textbook. Here are free, legal alternatives that cover the same core material for undergraduate physical chemistry.",
    category: 'Sciences',
    readTime: '7 min',
    date: 'Feb 6, 2026',
    content: [
      { type: 'p', text: "Atkins' Physical Chemistry is one of the most widely assigned textbooks in undergraduate chemistry, and new editions regularly run well over $150. The core subject — thermodynamics, quantum chemistry, kinetics, spectroscopy — is standard enough that several free, rigorous alternatives cover the same ground." },
      { type: 'h2', text: 'Free full courses and texts' },
      { type: 'book', title: 'Physical Chemistry (OpenStax / LibreTexts collections)', author: 'Multiple contributing authors', note: 'LibreTexts hosts an actively maintained, free, peer-reviewed physical chemistry textbook collection covering thermodynamics, quantum mechanics, and kinetics at the same depth as standard commercial texts.' },
      { type: 'book', title: '5.61 Physical Chemistry (MIT OpenCourseWare)', author: 'MIT Department of Chemistry', note: 'Full lecture notes, problem sets, and exams from MIT\'s undergraduate physical chemistry sequence, free and complete.' },
      { type: 'h2', text: 'Filling in specific topics' },
      { type: 'ul', items: [
        'Thermodynamics: search for free thermodynamics texts from MIT OCW or LibreTexts — the derivations match what Atkins covers chapter-for-chapter.',
        'Quantum chemistry: MIT\'s 5.61 and 5.73 courses cover this in more mathematical depth than most undergraduate texts, useful if Atkins feels too brief.',
        'Spectroscopy: search open-access spectroscopy course notes from any research university chemistry department — these are commonly published openly since the content changes little year to year.',
      ] },
      { type: 'tip', text: 'Physical chemistry problem sets are where courses actually differ most — pair a free textbook for concepts with your assigned course\'s specific problem sets rather than trying to match both exactly.' },
    ],
  },
  {
    slug: 'author-payout-models-explained',
    title: 'How Author Payout Models Actually Work: An Honest Comparison',
    description: 'Royalty percentages, ad-revenue sharing, reader-engagement payouts — a plain-language look at how different self-publishing and creator platforms actually pay authors.',
    category: 'For Authors',
    readTime: '9 min',
    date: 'Feb 8, 2026',
    content: [
      { type: 'p', text: "Every self-publishing platform advertises its payout terms differently, which makes them hard to compare. Some quote a royalty percentage of sale price. Some pay per page read. Some share ad revenue. This is a plain look at how the major models actually work, without picking a side." },
      { type: 'h2', text: 'Per-sale royalty models' },
      { type: 'p', text: 'The traditional model: a fixed percentage of each sale, typically 35–70% depending on price tier and exclusivity terms. The advantage is predictability — you know exactly what a sale is worth. The disadvantage is that it only pays when someone completes a purchase decision, and price competition in a crowded market pushes prices (and therefore per-sale earnings) down over time.' },
      { type: 'h2', text: 'Pages-read / engagement models' },
      { type: 'p', text: 'Some platforms pay from a shared fund divided by total pages read across all participating books that month. This rewards books that keep readers engaged all the way through, rather than just books that get purchased and abandoned. The tradeoff: your payout per page depends on how many other authors are also being read that month, which authors can\'t control or predict in advance.' },
      { type: 'h2', text: 'Ad-revenue sharing models' },
      { type: 'p', text: 'A smaller number of platforms — ANYFREEBOOK among them — remove the purchase decision entirely: readers access work for free, and a share of platform ad revenue (in ANYFREEBOOK\'s case, 40%) is distributed to authors based on verified reading engagement. This trades the ceiling of a per-copy sale for a much larger pool of potential readers, since there\'s no price barrier to someone starting your book.' },
      { type: 'ul', items: [
        'Per-sale royalty: higher ceiling per reader, but a real barrier — someone has to decide to pay before they ever read a word.',
        'Pages-read funds: rewards genuinely engaging books, but payout per page varies month to month.',
        'Ad-revenue sharing: removes the purchase barrier entirely, trades per-reader ceiling for reach.',
      ] },
      { type: 'tip', text: 'None of these models is objectively "better" — they optimize for different things. An author writing genre fiction for a broad audience and an author writing a niche technical guide will often see very different results from the same model.' },
    ],
  },
  {
    slug: 'public-domain-classics-reading-list',
    title: '20 Public Domain Classics Everyone Should Read for Free',
    description: 'A reading list of genuinely great public-domain novels — no filler, no obscure padding, just the classics that earned their reputation and cost nothing to read legally.',
    category: 'Literature',
    readTime: '10 min',
    date: 'Feb 10, 2026',
    content: [
      { type: 'p', text: 'Public domain lists often pad themselves with obscure Victorian novels nobody actually enjoys just to hit a round number. This list skips that — these are books that are genuinely worth reading, that also happen to be completely free because their copyright has expired.' },
      { type: 'h2', text: 'Where to start if you\'ve never read a "classic" for fun' },
      { type: 'book', title: 'Pride and Prejudice', author: 'Jane Austen', note: 'Sharper and funnier than its reputation as "serious literature" suggests — Austen\'s dialogue holds up better than most 21st-century sitcoms.' },
      { type: 'book', title: 'The Adventures of Sherlock Holmes', author: 'Arthur Conan Doyle', note: 'Short stories, not a novel — easy to read one at a time. Still the template every detective story since has borrowed from.' },
      { type: 'h2', text: 'For readers who want something denser' },
      { type: 'book', title: 'Crime and Punishment', author: 'Fyodor Dostoevsky', note: 'A genuine psychological thriller disguised as 19th-century Russian literature. Longer commitment, worth it.' },
      { type: 'book', title: 'Frankenstein', author: 'Mary Shelley', note: 'Wildly different from every film adaptation — the creature is articulate and the moral questions are far more uncomfortable than the pop-culture version suggests.' },
      { type: 'h2', text: 'Short and underrated' },
      { type: 'book', title: 'The Yellow Wallpaper', author: 'Charlotte Perkins Gilman', note: 'A short story, readable in one sitting, and one of the sharpest critiques of 19th-century medicine ever written.' },
      { type: 'book', title: 'Heart of Darkness', author: 'Joseph Conrad', note: 'Short, dense, and the direct inspiration for Apocalypse Now — worth reading with awareness of its colonial-era framing.' },
      { type: 'tip', text: 'Public domain status depends on the author\'s death date and varies by country — most pre-1928 English-language works are safely public domain in the US, but always check local copyright term if you\'re outside the US.' },
    ],
  },
  {
    slug: 'free-poetry-collections-worth-reading',
    title: 'Free Poetry Collections Actually Worth Reading Online',
    description: 'Skip the random single-poem blog posts — full public-domain poetry collections, from accessible to challenging, that are free to read in their entirety.',
    category: 'Poetry',
    readTime: '6 min',
    date: 'Feb 12, 2026',
    content: [
      { type: 'p', text: 'Most "free poetry" search results are single poems scattered across quote-aggregator sites with no context. Full collections, read as their poets intended, are a different experience — here are ones worth reading start to finish.' },
      { type: 'book', title: 'Leaves of Grass', author: 'Walt Whitman', note: 'Whitman revised this collection across his entire life — later editions are richer, but the original 1855 edition has a raw energy the later versions smooth over.' },
      { type: 'book', title: 'The Complete Poems of Emily Dickinson', author: 'Emily Dickinson', note: 'Best read in short sessions, not all at once — the poems are dense and reward slow reading over a marathon.' },
      { type: 'book', title: 'Sonnets from the Portuguese', author: 'Elizabeth Barrett Browning', note: 'A tightly focused sonnet sequence about falling in love — much shorter and more accessible than most 19th-century poetry.' },
      { type: 'h2', text: 'For a different tradition' },
      { type: 'p', text: 'Public domain poetry in translation opens up entirely different traditions — classical Persian, Chinese, and Japanese poetry all have public-domain English translations worth seeking out, though translation quality varies significantly between editions, so it\'s worth comparing more than one if a particular poem matters to you.' },
      { type: 'tip', text: 'ANYFREEBOOK\'s Poetry & Rhymes category pulls live results across these and many more collections in one search.' },
    ],
  },
  {
    slug: 'free-waec-jamb-study-resources',
    title: 'Free Study Resources for WAEC and JAMB Preparation',
    description: 'A practical guide to legitimate free study materials for WAEC and JAMB exam preparation — past questions, syllabus-aligned texts, and how to structure a study plan.',
    category: 'Education',
    readTime: '8 min',
    date: 'Feb 14, 2026',
    content: [
      { type: 'p', text: 'WAEC and JAMB preparation materials are sold aggressively, but a genuine amount of useful, syllabus-aligned free material exists if you know how to filter it from low-quality copies.' },
      { type: 'h2', text: 'What actually helps' },
      { type: 'ul', items: [
        'Past questions matter more than any single textbook — pattern familiarity is most of the exam-readiness battle for both WAEC and JAMB.',
        'The official syllabus documents (published by WAEC and JAMB directly) are free and specify exactly what\'s examinable — starting a study plan from an unofficial guide instead of the syllabus wastes time on material that isn\'t tested.',
        'Free OpenStax and open-access textbooks cover most core subjects (biology, chemistry, physics, economics, government) at a level that maps closely onto WAEC/JAMB syllabus requirements, even though they weren\'t written specifically for these exams.',
      ] },
      { type: 'h2', text: 'Structuring a study plan' },
      { type: 'p', text: 'Work backward from the exam date: allocate the first half of your remaining time to working through syllabus topics you haven\'t covered, and the second half almost entirely to past questions under timed conditions. Most students over-invest in reading and under-invest in timed practice, which is the actual skill being tested.' },
      { type: 'tip', text: 'ANYFREEBOOK\'s WAEC & JAMB resources page collects curated official and open-access study material in one place, updated as new resources become available.' },
    ],
  },
  {
    slug: 'free-french-literature-original-and-translation',
    title: 'Free French Literature: Reading in the Original vs. Translation',
    description: 'Where to find classic French literature free online, and an honest look at when reading in the original is worth the effort versus reading a good translation.',
    category: 'Languages',
    readTime: '7 min',
    date: 'Feb 16, 2026',
    content: [
      { type: 'p', text: 'French literature has an unusually large public-domain catalog because copyright terms have expired on most major 19th-century work, and French digitization projects (particularly Gallica, the French national library\'s archive) are extensive. The real question for most readers isn\'t availability — it\'s whether to read in French or translation.' },
      { type: 'h2', text: 'Free in the original French' },
      { type: 'book', title: 'Le Comte de Monte-Cristo', author: 'Alexandre Dumas', note: 'Long, but Dumas writes in genuinely accessible French — a reasonable choice for intermediate French readers wanting to try a full novel.' },
      { type: 'book', title: 'Madame Bovary', author: 'Gustave Flaubert', note: 'Denser prose than Dumas — better attempted after some experience reading French novels, not as a first attempt.' },
      { type: 'h2', text: 'When translation is the better choice' },
      { type: 'p', text: 'Poetry and wordplay-heavy prose lose the most in translation — but if your French isn\'t at a level where you can read fluently without constant dictionary lookups, a good translation will get you the actual story and ideas faster than a frustrating slog through the original. Read translated first, original later once you\'re more comfortable, rather than forcing the original as a beginner.' },
      { type: 'tip', text: 'ANYFREEBOOK\'s Books in French and French Literature categories both surface live results — the first for French-language originals, the second includes English translations as well.' },
    ],
  },
  {
    slug: 'how-to-host-free-live-online-class',
    title: 'How to Host a Free Live Online Class: A Practical Guide',
    description: 'A step-by-step guide for educators and authors wanting to host live online classes without expensive video software or a technical setup.',
    category: 'Teaching',
    readTime: '7 min',
    date: 'Feb 18, 2026',
    content: [
      { type: 'p', text: "Hosting a live online class used to require either expensive webinar software or wrestling with video conferencing tools not built for teaching. Here's a practical walkthrough of what actually matters for a good live class, regardless of which platform you use." },
      { type: 'h2', text: 'Before you go live' },
      { type: 'ul', items: [
        'Test your camera and microphone a few minutes before start time, not the moment class begins — audio problems are the single most common thing that derails a live class.',
        'Have your material (slides, a document, or a book you\'re teaching from) ready to share before you start, not mid-class.',
        'Decide in advance whether your class is public (open to anyone who finds it) or private (invite-link only) — this changes how you should promote it.',
      ] },
      { type: 'h2', text: 'During the class' },
      { type: 'p', text: "Live chat is your most valuable tool for gauging whether people are following along — silence doesn't mean people are lost, but a complete absence of chat activity for a long stretch usually means it's worth pausing to check in directly." },
      { type: 'h2', text: 'Choosing a platform' },
      { type: 'p', text: 'Free platforms exist that don\'t require attendees to sign up for anything or download software — ANYFREEBOOK\'s classroom feature, for example, runs entirely in-browser for both host and viewers, with document sharing built in so you can teach directly from a book or set of notes without switching windows.' },
      { type: 'tip', text: 'Start small. A first live class with five real attendees who stay engaged is more valuable than a poorly-run session with fifty who leave halfway through.' },
    ],
  },
  {
    slug: 'free-philosophy-books-that-change-thinking',
    title: '15 Free Philosophy Books That Actually Change How You Think',
    description: 'Skip the intimidating survey textbooks — these free, public-domain philosophy books are genuinely readable and worth the time, from ancient to modern.',
    category: 'Philosophy',
    readTime: '9 min',
    date: 'Feb 20, 2026',
    content: [
      { type: 'p', text: 'Philosophy has a reputation for being inaccessible, and some of it deserves that reputation. But a real subset of foundational philosophy is genuinely readable without a background in the field — and almost all of it, being centuries old, is completely free.' },
      { type: 'h2', text: 'Ancient philosophy — surprisingly practical' },
      { type: 'book', title: 'Meditations', author: 'Marcus Aurelius', note: 'Written as private notes to himself, not for publication — reads more like a journal than a treatise, and is one of the most accessible entry points into Stoic philosophy.' },
      { type: 'book', title: 'The Enchiridion', author: 'Epictetus', note: 'Short, direct, practical — closer to a set of life rules than abstract philosophy.' },
      { type: 'h2', text: 'Modern philosophy that reads clearly' },
      { type: 'book', title: 'On Liberty', author: 'John Stuart Mill', note: 'Still one of the clearest, most directly argued defenses of individual freedom ever written — genuinely readable without prior philosophy background.' },
      { type: 'book', title: 'Beyond Good and Evil', author: 'Friedrich Nietzsche', note: 'Denser and more challenging than the others on this list, written in aphorisms rather than sustained argument — better as a second or third philosophy book, not a first.' },
      { type: 'h2', text: 'A practical way to start' },
      { type: 'p', text: 'Start with Meditations or The Enchiridion regardless of what draws you to philosophy generally — both are short, were never meant to be intimidating, and give you a real feel for philosophical thinking before you tackle anything longer.' },
      { type: 'tip', text: 'Read philosophy slower than fiction — a page of dense argument often needs re-reading, and that\'s normal, not a sign you\'re reading wrong.' },
    ],
  },
  {
    slug: 'free-business-startup-books-for-founders',
    title: 'Free Business and Startup Books Every First-Time Founder Should Read',
    description: 'Business bestsellers are expensive and often padded. Here are genuinely useful, freely available business and economics books for first-time founders.',
    category: 'Business',
    readTime: '8 min',
    date: 'Feb 22, 2026',
    content: [
      { type: 'p', text: "Most bestselling business books cost $20–30 and could be a long-form blog post. A smaller set of genuinely foundational business and economics writing is both more substantial and completely free, because it's old enough to be public domain or was released openly by its author or institution." },
      { type: 'h2', text: 'Foundational economics for founders' },
      { type: 'book', title: 'The Wealth of Nations', author: 'Adam Smith', note: 'Long, and you don\'t need all of it — Book I on the division of labor and markets is the most directly useful section for understanding how markets actually behave.' },
      { type: 'h2', text: 'Open, modern business resources' },
      { type: 'p', text: 'Several universities and business schools have released core strategy, marketing, and finance course material openly — MIT OpenCourseWare\'s Sloan School offerings in particular cover entrepreneurship and finance fundamentals at the same depth as paid MBA-adjacent courses.' },
      { type: 'ul', items: [
        'MIT OpenCourseWare\'s entrepreneurship and finance courses — free, complete, with problem sets.',
        'Open-access accounting fundamentals texts (search "principles of accounting open textbook") cover exactly what a first-time founder needs to read their own financial statements.',
        'Government small-business resources (in most countries) are free and often more directly applicable than general business bestsellers, since they\'re written for your specific regulatory environment.',
      ] },
      { type: 'h2', text: 'What to actually read first' },
      { type: 'p', text: "If you're pre-revenue, prioritize a free accounting fundamentals resource over strategy books — understanding your own numbers matters more at this stage than frameworks for decisions you're not ready to make yet." },
      { type: 'tip', text: 'ANYFREEBOOK\'s Business and Entrepreneurship categories aggregate current free titles across these areas, refreshed automatically.' },
    ],
  },
  {
    slug: 'free-engineering-textbooks-subject-guide',
    title: 'Free Engineering Textbooks: A Subject-by-Subject Guide',
    description: 'Engineering textbooks routinely cost $150–300. Here is where to find free, legitimate alternatives across mechanical, electrical, civil, and chemical engineering.',
    category: 'Engineering',
    readTime: '9 min',
    date: 'Feb 24, 2026',
    content: [
      { type: 'p', text: 'Engineering textbooks are some of the most expensive on any university book list, and new editions are released frequently enough that used copies don\'t stay cheap for long. The core material changes slowly, though, which means free alternatives stay usable for years.' },
      { type: 'h2', text: 'Mechanical engineering' },
      { type: 'p', text: 'MIT OpenCourseWare\'s mechanical engineering department has released full course material — lecture notes, problem sets, and often full video lectures — for statics, dynamics, thermodynamics, and materials science.' },
      { type: 'h2', text: 'Electrical engineering' },
      { type: 'book', title: 'Circuits and Electronics (MIT 6.002x course material)', author: 'MIT Department of EECS', note: 'Complete free course material covering circuit analysis fundamentals, the same core content as most introductory circuits textbooks.' },
      { type: 'h2', text: 'Civil engineering' },
      { type: 'p', text: 'Structural analysis and statics fundamentals are well covered by MIT and other OpenCourseWare offerings — search by specific topic (structural analysis, soil mechanics, fluid mechanics) rather than a general "civil engineering textbook" search, since the material is usually organized by course, not as a single omnibus text.' },
      { type: 'h2', text: 'Chemical engineering' },
      { type: 'ul', items: [
        'Search "chemical engineering thermodynamics open textbook" for free alternatives covering the same material as standard commercial texts.',
        'Process design and unit operations fundamentals are covered in several openly licensed university course packets, worth searching by specific topic.',
      ] },
      { type: 'tip', text: 'Engineering fundamentals (statics, thermodynamics, circuit theory) change far less between editions than the marketing suggests — a free text from a few years ago is almost always still fully usable for coursework.' },
    ],
  },
  {
    slug: 'free-books-swahili-amharic-zulu',
    title: 'Free Books in Swahili, Amharic, and Zulu: A Real Search Guide',
    description: 'Original literature and open texts in Swahili, Amharic, and Zulu exist online but rarely surface in general search. Here is where to actually look.',
    category: 'Languages',
    readTime: '7 min',
    date: 'Feb 26, 2026',
    content: [
      { type: 'p', text: 'East and Southern African languages have a real, if scattered, body of freely available literature — Swahili in particular has one of the largest literary traditions of any African language, given its role as a regional lingua franca across East Africa. Finding it online just takes knowing where to search.' },
      { type: 'h2', text: 'Swahili' },
      { type: 'p', text: 'Swahili has an unusually strong digitization effort compared to many African languages, partly driven by its use as an official language in Tanzania and Kenya and its status as a major regional language studied academically worldwide. University African-studies departments (particularly in the US and UK) often maintain open Swahili text archives.' },
      { type: 'book', title: 'Utenzi wa Vita vya Uhud', author: 'Traditional Swahili epic verse', note: 'A classical Swahili epic poem (utenzi) — an example of the long narrative-poem tradition that predates Swahili prose fiction. Search university Swahili-studies archives for digitized versions.' },
      { type: 'h2', text: 'Amharic' },
      { type: 'p', text: "Amharic literature is harder to find in digitized form outside Ethiopia itself, partly because its script (Ge'ez) requires specific font and encoding support that older digitization projects often didn't handle well. This is improving — search recent university archive projects rather than older general book-scanning efforts, which are more likely to have skipped non-Latin scripts entirely." },
      { type: 'h2', text: 'Zulu' },
      { type: 'book', title: 'Chaka', author: 'Thomas Mofolo', note: 'Technically written in Sesotho rather than Zulu, but this early 20th-century historical novel about the Zulu king Shaka is a foundational text of Southern African literature worth knowing about regardless of which of the two languages you\'re searching for.' },
      { type: 'h2', text: 'How to search effectively across all three' },
      { type: 'ul', items: [
        'Search using the ISO language code (sw, am, zu) alongside your query on Open Library and Internet Archive — both support language filtering, and the code catches results a plain-language search misses.',
        'University African-studies department library pages, not general search engines, are often the actual gateway to non-Latin-script digitization projects.',
        'ANYFREEBOOK\'s Books in Swahili, Books in Amharic, and Books in Zulu categories pull live results from these sources automatically as new scans are added.',
      ] },
      { type: 'tip', text: 'If you\'re specifically looking for oral-tradition material (epics, praise poetry) rather than novels, search for "utenzi" (Swahili), specific Ethiopian oral literature terms, or "izibongo" (Zulu praise poetry) rather than generic fiction search terms.' },
    ],
  },
  {
    slug: 'best-free-kenyan-south-african-ghanaian-literature',
    title: 'The Best Free Kenyan, South African, and Ghanaian Literature',
    description: 'Beyond Nigerian literature — free, public-domain, and open-access writing from Kenya, South Africa, and Ghana worth reading.',
    category: 'African Literature',
    readTime: '8 min',
    date: 'Feb 28, 2026',
    content: [
      { type: 'p', text: 'Nigerian literature tends to dominate "African literature" reading lists, partly because of its sheer output and partly because of a handful of internationally famous names. Kenyan, South African, and Ghanaian writing is just as rich and often less crowded — worth seeking out specifically.' },
      { type: 'h2', text: 'Kenya' },
      { type: 'p', text: "Kenyan literature in English has a strong early tradition, though much of the most politically significant work from the independence and post-independence era exists more readily in university archives than general search results, since it was often published in small runs by regional presses." },
      { type: 'h2', text: 'South Africa' },
      { type: 'p', text: 'South African literature from the apartheid era is unusually well documented and digitized compared to much of the continent, partly due to significant international academic interest — search terms like "South African apartheid-era literature archive" surface more than general fiction searches.' },
      { type: 'book', title: 'Mhudi', author: 'Sol Plaatje', note: 'Widely regarded as the first novel in English published by a Black South African author (written around 1920, published 1930) — a historically foundational text, worth searching university and national archive digitization projects for.' },
      { type: 'h2', text: 'Ghana' },
      { type: 'p', text: "Ghanaian literature has a strong post-independence tradition, and Ghana's status as the first Sub-Saharan African country to gain independence (1957) means a real body of early nation-building era writing exists — essays, speeches, and early fiction — much of which is now old enough to be entering the public domain." },
      { type: 'h2', text: 'Where to search across all three' },
      { type: 'p', text: 'ANYFREEBOOK\'s Kenyan Literature, South African Literature, and Ghanaian Literature categories aggregate live results across Open Library, Internet Archive, and Google Books, which is the most efficient starting point given how scattered individual archives are.' },
      { type: 'tip', text: 'For apartheid-era South African literature specifically, note that some works were banned in South Africa at the time of publication but published abroad — search international as well as South African archive sources.' },
    ],
  },
  {
    slug: 'free-alternative-stewart-calculus',
    title: "Free Alternatives to Stewart's Calculus",
    description: "James Stewart's Calculus textbook is a near-universal assignment and costs $250+. Here are free, rigorous alternatives covering the same material.",
    category: 'Sciences',
    readTime: '7 min',
    date: 'Mar 2, 2026',
    content: [
      { type: 'p', text: "Stewart's Calculus is assigned in more first-year calculus courses than almost any other textbook, and current editions regularly list above $250. The subject matter — limits, derivatives, integrals, series — is completely standard across institutions, which means free alternatives cover essentially identical ground." },
      { type: 'h2', text: 'Full free textbooks' },
      { type: 'book', title: 'Calculus (OpenStax)', author: 'OpenStax contributors', note: 'A complete, free, peer-reviewed calculus sequence (Volumes 1-3) covering single and multivariable calculus at the same depth and rigor as Stewart, with a similar problem-set structure.' },
      { type: 'book', title: 'Calculus (Gilbert Strang, MIT OpenCourseWare)', author: 'Gilbert Strang', note: 'MIT\'s freely released calculus textbook, written by a widely respected mathematics educator — a genuinely good text on its own merits, not just a free substitute.' },
      { type: 'h2', text: 'If you specifically need practice problems' },
      { type: 'p', text: 'MIT OpenCourseWare\'s 18.01 (Single Variable Calculus) and 18.02 (Multivariable Calculus) courses include full problem sets with solutions, which is often the actual gap when using a free textbook instead of an assigned one — the concepts transfer easily, but matching problem-set difficulty and style takes a bit more searching.' },
      { type: 'h2', text: 'Matching a Stewart-based course to a free text' },
      { type: 'p', text: 'Stewart\'s chapter order (limits → derivatives → applications → integrals → series) is close to universal in American calculus education, and OpenStax follows nearly the same sequence, which makes it easy to read the free chapter alongside your assigned Stewart chapter number for number.' },
      { type: 'tip', text: 'Calculus notation and conventions are extremely standardized — unlike some subjects, there\'s very little risk of a free alternative teaching a genuinely different approach that conflicts with your course.' },
    ],
  },
  {
    slug: 'free-classic-russian-literature-reading-list',
    title: 'A Reading List of Free Classic Russian Literature',
    description: 'Russian literature has an unusually large public-domain catalog. Here is where to start, organized by length and difficulty.',
    category: 'Literature',
    readTime: '8 min',
    date: 'Mar 4, 2026',
    content: [
      { type: 'p', text: "Russian literature's 19th-century golden age is almost entirely public domain now, and it's some of the most highly regarded fiction ever written — but the reputation for difficulty (long books, long names, philosophical density) puts a lot of readers off before they start. Here's a path through it that doesn't start with the hardest option." },
      { type: 'h2', text: 'Start here, not with Dostoevsky' },
      { type: 'book', title: 'The Death of Ivan Ilyich', author: 'Leo Tolstoy', note: 'A novella, not a doorstop — reads in an afternoon and is a genuinely better introduction to Tolstoy\'s concerns than starting cold with War and Peace.' },
      { type: 'book', title: 'The Overcoat', author: 'Nikolai Gogol', note: 'A short story often cited as foundational to all later Russian prose fiction — darkly funny, quick to read, and a useful preview of Gogol\'s sensibility before attempting a longer work.' },
      { type: 'h2', text: 'The famous long ones — worth the time' },
      { type: 'book', title: 'Crime and Punishment', author: 'Fyodor Dostoevsky', note: 'The most approachable of Dostoevsky\'s major novels — structured more like a psychological thriller than his later, more philosophically dense work.' },
      { type: 'book', title: 'Anna Karenina', author: 'Leo Tolstoy', note: 'Long, but the plot moves faster than its reputation suggests. A more emotionally direct read than War and Peace, and a reasonable choice for a first full-length Tolstoy novel.' },
      { type: 'h2', text: 'A note on translations' },
      { type: 'p', text: 'Translation choice matters more for Russian literature than for most languages — older public-domain English translations (many from the early 20th century) are freely available but can feel stiff compared to modern translations, which are usually still under copyright. The free versions are completely readable; just don\'t assume the prose style reflects the original Russian if it feels dated.' },
      { type: 'tip', text: 'If a long Russian novel feels slow at first, that\'s often the translation and the unfamiliar naming conventions (patronymics, nicknames) rather than the writing itself — a short glossary of character names, kept nearby for the first fifty pages, solves most of the early confusion.' },
    ],
  },
  {
    slug: 'best-free-resources-learning-new-language',
    title: 'The Best Free Resources for Learning a New Language',
    description: 'Free grammar guides, dictionaries, and graded readers for language learners — not app gamification, actual reference material that works.',
    category: 'Languages',
    readTime: '7 min',
    date: 'Mar 6, 2026',
    content: [
      { type: 'p', text: 'Language-learning apps get most of the attention, but a lot of serious language learning still happens through grammar reference books, dictionaries, and graded readers — and a meaningful number of solid ones are completely free, particularly for widely studied languages.' },
      { type: 'h2', text: 'Reference grammars' },
      { type: 'p', text: 'Older, out-of-copyright grammar reference books (particularly for French, German, Spanish, Latin, and Ancient Greek) remain genuinely useful — grammar doesn\'t change the way vocabulary or pronunciation trends do, so a public-domain grammar from decades ago is often just as accurate as a new one, just less visually polished.' },
      { type: 'h2', text: 'Graded readers' },
      { type: 'p', text: 'Reading material written for learners at a specific level — not native-speaker literature, not a phrasebook — is one of the most underused free resources. Simplified versions of public-domain classics exist for several major languages and bridge the gap between "textbook exercises" and "real literature" better than either extreme.' },
      { type: 'h2', text: 'Dictionaries' },
      { type: 'p', text: 'Public-domain bilingual dictionaries exist for most major language pairs, and while modern dictionaries add newer vocabulary, a public-domain dictionary from the early-to-mid 20th century is still fully usable for the vast majority of everyday and literary vocabulary.' },
      { type: 'ul', items: [
        'Search "[language] grammar reference" plus "open access" or "public domain" rather than general search — this filters out paid course platforms.',
        'University language departments frequently publish free grammar guides and reading lists for their own courses, openly accessible even to non-students.',
        'ANYFREEBOOK\'s Languages & Grammar category surfaces live results across open grammar references and bilingual texts.',
      ] },
      { type: 'tip', text: 'Reading a public-domain novel in your target language, even slowly with a dictionary at hand, builds vocabulary retention better than isolated flashcard review — the context does real work that memorization alone doesn\'t.' },
    ],
  },
  {
    slug: 'free-mythology-folklore-collections',
    title: 'Free Mythology and Folklore Collections Worth Reading',
    description: 'Full collections of world mythology and folklore, free and public domain — Greek, Norse, and beyond, organized by where to start.',
    category: 'Mythology',
    readTime: '7 min',
    date: 'Mar 8, 2026',
    content: [
      { type: 'p', text: 'Mythology retellings dominate bestseller lists, but the original source collections — the actual texts these retellings draw from — are almost entirely free and public domain, and often more interesting than the modern adaptations.' },
      { type: 'h2', text: 'Greek and Roman' },
      { type: 'book', title: "Bulfinch's Mythology", author: 'Thomas Bulfinch', note: 'A 19th-century compilation that remains one of the most readable single-volume introductions to Greek and Roman mythology — organized thematically rather than as a dense academic reference.' },
      { type: 'book', title: 'Metamorphoses', author: 'Ovid (public domain translations)', note: 'The actual Roman source text behind most Greek mythology retellings you\'ve read — narrative poetry, genuinely entertaining rather than dry, though translation quality varies significantly between editions.' },
      { type: 'h2', text: 'Norse' },
      { type: 'book', title: 'The Prose Edda', author: 'Snorri Sturluson (public domain translations)', note: 'The primary source for most Norse mythology as it\'s commonly known today — shorter and more approachable than it sounds, structured as a set of connected stories rather than a dense reference work.' },
      { type: 'h2', text: 'Beyond Greek and Norse' },
      { type: 'p', text: "Public domain folklore collections exist for many other traditions too — 19th and early 20th-century folklorists and anthropologists compiled extensive collections of oral tradition from around the world, though it's worth reading these with awareness of the colonial-era framing many were written in." },
      { type: 'tip', text: 'ANYFREEBOOK\'s Mythology category pulls live results across these and other traditions — search a specific culture or pantheon name for the most targeted results.' },
    ],
  },
  {
    slug: 'free-world-history-books-that-read-like-a-story',
    title: 'Free World History Books That Actually Read Like a Story',
    description: 'History books that read more like narrative than textbook — free, public-domain, and genuinely engaging rather than a chronology of dates.',
    category: 'History',
    readTime: '8 min',
    date: 'Mar 10, 2026',
    content: [
      { type: 'p', text: 'Most free history resources people find are dry academic textbooks or Wikipedia summaries. A real category of narrative history writing — history told with the pacing and voice of a story, not a chronology — exists in the public domain and is worth specifically seeking out.' },
      { type: 'h2', text: 'Classic narrative historians' },
      { type: 'book', title: 'The History of the Decline and Fall of the Roman Empire', author: 'Edward Gibbon', note: 'Long, and the prose style is 18th-century formal, but Gibbon\'s narrative voice — opinionated, dry-witted, genuinely engaging — set the template for readable popular history that\'s still followed today.' },
      { type: 'book', title: 'The Histories', author: 'Herodotus (public domain translations)', note: "Often called the first work of history in the Western tradition — full of digressions, gossip, and genuine storytelling rather than dry chronology, closer to a travelogue than a textbook." },
      { type: 'h2', text: 'First-hand accounts' },
      { type: 'p', text: 'Memoirs and first-hand accounts from historical figures are underused as history reading — they read naturally as narrative because they are narrative, written by someone who was actually there, and a substantial number from before the mid-20th century are now public domain.' },
      { type: 'h2', text: 'Where to search' },
      { type: 'p', text: 'ANYFREEBOOK\'s History category aggregates live results across these and thousands of other public-domain and open-access history texts, updated continuously as archives add new scans.' },
      { type: 'tip', text: 'Older narrative histories reflect the biases and gaps of when they were written — genuinely engaging to read, but worth pairing with a modern overview if you want a fuller, more balanced picture of the same period.' },
    ],
  },
  {
    slug: 'free-psychology-books-worth-reading',
    title: 'Free Psychology Books Worth Reading (Beyond the Textbook)',
    description: 'Free psychology reading that goes beyond the intro-course textbook — foundational texts and genuinely readable classics in the field.',
    category: 'Psychology',
    readTime: '7 min',
    date: 'Mar 12, 2026',
    content: [
      { type: 'p', text: 'Introductory psychology textbooks summarize the field but rarely let you read the foundational thinkers directly. A surprising number of psychology\'s founding texts are now public domain, and read very differently from a modern textbook\'s tidy summary of them.' },
      { type: 'h2', text: 'Foundational texts' },
      { type: 'book', title: 'The Interpretation of Dreams', author: 'Sigmund Freud (public domain translations)', note: 'Whatever your view of Freud\'s conclusions, this is a foundational text that shaped an entire field — worth reading directly rather than only through secondhand summary, if only to see what he actually argued versus what\'s commonly attributed to him.' },
      { type: 'book', title: 'The Principles of Psychology', author: 'William James', note: 'Long, but James is a genuinely excellent prose stylist — this remains one of the most readable foundational psychology texts, still cited constantly in modern research.' },
      { type: 'h2', text: 'Behaviorism and beyond' },
      { type: 'p', text: 'Early behaviorist texts (Watson, and later Skinner\'s foundational work once it enters the public domain) are worth reading directly if you\'ve only encountered behaviorism as a textbook\'s brief historical footnote before moving on to cognitive psychology — the original arguments are more nuanced than the summary version.' },
      { type: 'h2', text: 'Reading these critically' },
      { type: 'p', text: "A lot of early psychology has been significantly revised or outright rejected by modern research — read these as intellectual history and a window into how the field developed, not as current best evidence. That context makes them more interesting, not less." },
      { type: 'tip', text: "ANYFREEBOOK's Psychology category surfaces live results across these and other open-access psychology texts, filterable alongside modern open-access research where available." },
    ],
  },
  {
    slug: 'reading-anyfreebook-in-your-own-language',
    title: 'How to Read ANYFREEBOOK in Your Own Language',
    description: 'A guide to using the site-wide translation feature — how it works, what it covers, and how to get the most accurate results.',
    category: 'Guides',
    readTime: '5 min',
    date: 'Mar 14, 2026',
    content: [
      { type: 'p', text: 'ANYFREEBOOK\'s interface and content can be translated on the fly into 30+ languages directly from the navigation bar — this is a quick guide to how it actually works and how to get the best results from it.' },
      { type: 'h2', text: 'How to turn it on' },
      { type: 'p', text: 'Look for the language picker (🌐) in the navigation bar, on both desktop and mobile. Selecting a language translates the visible interface and page content — it remembers your choice for future visits until you switch it back.' },
      { type: 'h2', text: 'What gets translated' },
      { type: 'ul', items: [
        'Site navigation, buttons, and interface text.',
        'Article and blog post content written in English.',
        'Dynamically loaded content, like the rotating homepage book grid — the translation keeps working as new content loads in, not just on the initial page load.',
      ] },
      { type: 'h2', text: 'What stays in its original language' },
      { type: 'p', text: 'Book titles and author names generally stay as published — translating a title can make it harder to find the actual book at its source, so those are deliberately left alone even when the surrounding description is translated.' },
      { type: 'h2', text: 'A note on translation quality' },
      { type: 'p', text: "This is machine translation, which is genuinely good for understanding meaning but won't always read as naturally as content originally written in that language — useful for quickly understanding what a page says, not a substitute for content actually authored in your language." },
      { type: 'tip', text: "If you'd rather read books actually written in a specific language rather than translated interface text, ANYFREEBOOK's language-specific book categories (Books in French, Books in Swahili, and 30+ others) are a better starting point than the translation feature." },
    ],
  },
  {
    slug: 'free-short-story-collections-for-busy-readers',
    title: 'Free Short Story Collections for Readers Short on Time',
    description: 'Full short story collections, free and public domain, for readers who want a complete story without committing to a full novel.',
    category: 'Fiction',
    readTime: '6 min',
    date: 'Mar 16, 2026',
    content: [
      { type: 'p', text: "A short story collection is one of the most underrated free-reading formats — a complete, satisfying story in one sitting, with the freedom to read one and stop, or several in a row. Here are collections worth starting with." },
      { type: 'book', title: 'The Adventures of Sherlock Holmes', author: 'Arthur Conan Doyle', note: 'Each story is genuinely self-contained — a strong choice if you want to dip in and out over weeks rather than reading straight through.' },
      { type: 'book', title: 'The Complete Short Stories', author: 'Anton Chekhov (public domain translations)', note: 'Chekhov is often cited as the master of the short story form specifically — quieter and more character-driven than a mystery collection, worth reading a few at a time rather than in bulk.' },
      { type: 'book', title: 'The Signal-Man and Other Stories', author: 'Charles Dickens', note: "Dickens's short fiction is less well known than his novels but genuinely good — and far less of a time commitment than tackling something like Bleak House." },
      { type: 'h2', text: 'Why short stories work well as free reading' },
      { type: 'p', text: "You get a complete narrative arc — beginning, middle, end — in the time it takes to read one chapter of a novel, which makes short story collections a good fit for reading in small windows of free time rather than needing a long uninterrupted stretch." },
      { type: 'tip', text: "ANYFREEBOOK's Short Stories category aggregates live results across these and many more collections, updated as new public-domain scans are added." },
    ],
  },
  {
    slug: 'introducing-anyfreebook-live-classrooms',
    title: 'Introducing Live Classrooms on ANYFREEBOOK',
    description: 'ANYFREEBOOK now has free live classrooms built directly into the platform — video, chat, and document sharing, with no software to install and no account required to watch.',
    category: 'Announcements',
    readTime: '6 min',
    date: 'Mar 18, 2026',
    content: [
      { type: 'p', text: "ANYFREEBOOK now has live classrooms built directly into the platform. Any author or educator on the site can start a free live class — video, live chat, and document sharing — and anyone can join and watch without creating an account or installing anything." },
      { type: 'h2', text: 'What it actually does' },
      { type: 'ul', items: [
        'Host a live class straight from your browser — camera, microphone, and screen share, no downloads.',
        'Viewers join with a single click. No sign-up is required to watch or use the live chat.',
        'Share a document or slide deck directly in the class — including a published book or note you\'ve written on ANYFREEBOOK — so students see exactly what you\'re teaching from without switching windows.',
        'Choose public (listed and discoverable by anyone) or private (invite-link only) for each class.',
        'An accurate "watching now" count, visible to the host, based on real connected viewers rather than an estimate.',
      ] },
      { type: 'h2', text: 'Why it works the way it does' },
      { type: 'p', text: "Most free video-call tools require every participant to create an account, install an app, or at minimum sign in once before joining. That's a real barrier for a classroom where the goal is to remove friction between a teacher and whoever wants to learn — so classrooms on ANYFREEBOOK were built specifically so that watching a class takes exactly one click and nothing else." },
      { type: 'p', text: 'The connection between host and viewers runs directly over the browser\'s own video technology (WebRTC) rather than routing through a third-party video company\'s branded app — which is also why there\'s no cost passed on to either the teacher or the student.' },
      { type: 'h2', text: 'A practical note on scale' },
      { type: 'p', text: "Because video runs directly between the host and each viewer rather than through a large relay infrastructure, a single class comfortably supports a real study-group or classroom-sized audience. It's built for teaching a class, not broadcasting to a stadium — which matches what most educators actually need." },
      { type: 'h2', text: 'Who this is for' },
      { type: 'p', text: "If you've ever wanted to teach a free class — a study session before an exam, a walkthrough of a book you've published, a language lesson, office hours for students who can't afford a formal course — this removes the two biggest barriers: cost, and asking your audience to sign up for yet another account before they can just watch." },
      { type: 'tip', text: 'Browse currently scheduled and live classes, or start your own, from the Classrooms link in the navigation bar. No teaching credentials or approval process required — just a topic worth teaching.' },
    ],
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find(p => p.slug === slug);
}
