/**
 * World categories: literature by country/continent, books by language, and
 * deep subject shelves. Every entry carries a live-search `query` so its
 * category page pulls REAL books from Open Library / Internet Archive /
 * Google Books — no synthetic filler.
 *
 * Spec: [name, icon, query?, group?] — query defaults to the name.
 */

export type WorldCategorySpec = [name: string, icon: string, query?: string, group?: 'subject' | 'place' | 'language'];

export const WORLD_CATEGORY_SPECS: WorldCategorySpec[] = [
  // ---------- Literature by country & continent (~62) ----------
  ['Nigerian Literature', '🇳🇬', 'nigerian literature', 'place'],
  ['Kenyan Literature', '🇰🇪', 'kenyan literature', 'place'],
  ['South African Literature', '🇿🇦', 'south african literature', 'place'],
  ['Ghanaian Literature', '🇬🇭', 'ghana literature', 'place'],
  ['Egyptian Literature', '🇪🇬', 'egyptian literature', 'place'],
  ['Ethiopian Literature', '🇪🇹', 'ethiopian literature', 'place'],
  ['Moroccan Literature', '🇲🇦', 'moroccan literature', 'place'],
  ['Tanzanian Literature', '🇹🇿', 'tanzania literature', 'place'],
  ['Ugandan Literature', '🇺🇬', 'uganda literature', 'place'],
  ['Zimbabwean Literature', '🇿🇼', 'zimbabwe literature', 'place'],
  ['Senegalese Literature', '🇸🇳', 'senegal literature', 'place'],
  ['Cameroonian Literature', '🇨🇲', 'cameroon literature', 'place'],
  ['Algerian Literature', '🇩🇿', 'algerian literature', 'place'],
  ['Tunisian Literature', '🇹🇳', 'tunisian literature', 'place'],
  ['Rwandan Literature', '🇷🇼', 'rwanda literature', 'place'],
  ['Indian Literature', '🇮🇳', 'indian literature', 'place'],
  ['Chinese Literature', '🇨🇳', 'chinese literature', 'place'],
  ['Japanese Literature', '🇯🇵', 'japanese literature', 'place'],
  ['Korean Literature', '🇰🇷', 'korean literature', 'place'],
  ['Pakistani Literature', '🇵🇰', 'pakistani literature', 'place'],
  ['Bangladeshi Literature', '🇧🇩', 'bengali literature', 'place'],
  ['Sri Lankan Literature', '🇱🇰', 'sri lanka literature', 'place'],
  ['Filipino Literature', '🇵🇭', 'philippine literature', 'place'],
  ['Vietnamese Literature', '🇻🇳', 'vietnamese literature', 'place'],
  ['Thai Literature', '🇹🇭', 'thai literature', 'place'],
  ['Indonesian Literature', '🇮🇩', 'indonesian literature', 'place'],
  ['Malaysian Literature', '🇲🇾', 'malaysian literature', 'place'],
  ['Turkish Literature', '🇹🇷', 'turkish literature', 'place'],
  ['Persian Literature', '🇮🇷', 'persian literature', 'place'],
  ['Arabic Literature', '🕌', 'arabic literature', 'place'],
  ['Hebrew Literature', '🇮🇱', 'hebrew literature', 'place'],
  ['British Literature', '🇬🇧', 'english literature', 'place'],
  ['Irish Literature', '🇮🇪', 'irish literature', 'place'],
  ['Scottish Literature', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'scottish literature', 'place'],
  ['French Literature', '🇫🇷', 'french literature', 'place'],
  ['German Literature', '🇩🇪', 'german literature', 'place'],
  ['Spanish Literature', '🇪🇸', 'spanish literature', 'place'],
  ['Italian Literature', '🇮🇹', 'italian literature', 'place'],
  ['Portuguese Literature', '🇵🇹', 'portuguese literature', 'place'],
  ['Russian Literature', '🇷🇺', 'russian literature', 'place'],
  ['Polish Literature', '🇵🇱', 'polish literature', 'place'],
  ['Dutch Literature', '🇳🇱', 'dutch literature', 'place'],
  ['Greek Literature', '🇬🇷', 'greek literature', 'place'],
  ['Norwegian Literature', '🇳🇴', 'norwegian literature', 'place'],
  ['Swedish Literature', '🇸🇪', 'swedish literature', 'place'],
  ['Danish Literature', '🇩🇰', 'danish literature', 'place'],
  ['Finnish Literature', '🇫🇮', 'finnish literature', 'place'],
  ['Czech Literature', '🇨🇿', 'czech literature', 'place'],
  ['Hungarian Literature', '🇭🇺', 'hungarian literature', 'place'],
  ['Romanian Literature', '🇷🇴', 'romanian literature', 'place'],
  ['Ukrainian Literature', '🇺🇦', 'ukrainian literature', 'place'],
  ['American Literature', '🇺🇸', 'american literature', 'place'],
  ['Canadian Literature', '🇨🇦', 'canadian literature', 'place'],
  ['Mexican Literature', '🇲🇽', 'mexican literature', 'place'],
  ['Brazilian Literature', '🇧🇷', 'brazilian literature', 'place'],
  ['Argentine Literature', '🇦🇷', 'argentine literature', 'place'],
  ['Chilean Literature', '🇨🇱', 'chilean literature', 'place'],
  ['Colombian Literature', '🇨🇴', 'colombian literature', 'place'],
  ['Peruvian Literature', '🇵🇪', 'peruvian literature', 'place'],
  ['Caribbean Literature', '🏝️', 'caribbean literature', 'place'],
  ['Australian Literature', '🇦🇺', 'australian literature', 'place'],
  ['New Zealand Literature', '🇳🇿', 'new zealand literature', 'place'],

  // ---------- Books by language (~34) ----------
  ['Books in French', '🗼', 'livres français', 'language'],
  ['Books in Spanish', '💃', 'libros español', 'language'],
  ['Books in Portuguese', '🌊', 'livros português', 'language'],
  ['Books in Arabic', '📿', 'كتب عربية', 'language'],
  ['Books in Swahili', '🦁', 'vitabu kiswahili', 'language'],
  ['Books in Yoruba', '🥁', 'yoruba language books', 'language'],
  ['Books in Igbo', '🌴', 'igbo language books', 'language'],
  ['Books in Hausa', '🐪', 'hausa language books', 'language'],
  ['Books in Amharic', '⛰️', 'amharic books', 'language'],
  ['Books in Zulu', '🛡️', 'zulu language books', 'language'],
  ['Books in Afrikaans', '🌍', 'afrikaans boeke', 'language'],
  ['Books in Hindi', '🪔', 'हिंदी पुस्तकें hindi books', 'language'],
  ['Books in Urdu', '🌙', 'urdu books', 'language'],
  ['Books in Bengali', '🐅', 'bengali books', 'language'],
  ['Books in Tamil', '🛕', 'tamil books', 'language'],
  ['Books in Chinese', '🏮', '中文书 chinese books', 'language'],
  ['Books in Japanese', '🗾', '日本語の本 japanese books', 'language'],
  ['Books in Korean', '🎎', '한국어 책 korean books', 'language'],
  ['Books in German', '🍺', 'deutsche bücher', 'language'],
  ['Books in Russian', '❄️', 'русские книги', 'language'],
  ['Books in Italian', '🍝', 'libri italiani', 'language'],
  ['Books in Dutch', '🌷', 'nederlandse boeken', 'language'],
  ['Books in Greek', '🏛️', 'ελληνικά βιβλία greek books', 'language'],
  ['Books in Turkish', '🫖', 'türkçe kitaplar', 'language'],
  ['Books in Persian', '🐆', 'کتاب فارسی persian books', 'language'],
  ['Books in Hebrew', '🕎', 'ספרים בעברית hebrew books', 'language'],
  ['Books in Polish', '🥟', 'polskie książki', 'language'],
  ['Books in Ukrainian', '🌻', 'українські книги', 'language'],
  ['Books in Vietnamese', '🍜', 'sách tiếng việt', 'language'],
  ['Books in Thai', '🐘', 'หนังสือไทย thai books', 'language'],
  ['Books in Indonesian', '🌋', 'buku bahasa indonesia', 'language'],
  ['Books in Tagalog', '🏖️', 'tagalog books', 'language'],
  ['Books in Latin', '🏺', 'latin language books', 'language'],
  ['Books in Esperanto', '⭐', 'esperanto books', 'language'],

  // ---------- Deep subject shelves (~104) ----------
  ['Astronomy', '🔭', 'astronomy'],
  ['Astrophysics', '🌌', 'astrophysics'],
  ['Geology', '🪨', 'geology'],
  ['Meteorology', '🌦️', 'meteorology weather'],
  ['Oceanography', '🌊', 'oceanography'],
  ['Ecology', '🌿', 'ecology'],
  ['Botany', '🌺', 'botany plants'],
  ['Zoology', '🦓', 'zoology animals'],
  ['Microbiology', '🦠', 'microbiology'],
  ['Genetics', '🧬', 'genetics'],
  ['Biochemistry', '⚗️', 'biochemistry'],
  ['Organic Chemistry', '🧪', 'organic chemistry'],
  ['Quantum Physics', '⚛️', 'quantum physics'],
  ['Statistics', '📊', 'statistics textbook'],
  ['Data Science', '📈', 'data science'],
  ['Artificial Intelligence', '🤖', 'artificial intelligence'],
  ['Machine Learning', '🧮', 'machine learning'],
  ['Web Development', '🕸️', 'web development programming'],
  ['Mobile Development', '📱', 'mobile app development'],
  ['Game Development', '🎮', 'game development programming'],
  ['Cybersecurity', '🔐', 'cybersecurity'],
  ['Computer Networking', '🌐', 'computer networking'],
  ['Databases', '🗄️', 'database systems'],
  ['Cloud Computing', '☁️', 'cloud computing'],
  ['Robotics', '🦾', 'robotics'],
  ['Electronics', '🔌', 'electronics circuits'],
  ['Renewable Energy', '🌞', 'renewable energy'],
  ['Environmental Science', '🌎', 'environmental science'],
  ['Climate Change', '🌡️', 'climate change'],
  ['Public Health', '🏥', 'public health'],
  ['Epidemiology', '🧫', 'epidemiology'],
  ['Human Anatomy', '🫀', 'human anatomy'],
  ['Physiology', '🫁', 'physiology'],
  ['Pharmacology', '💉', 'pharmacology'],
  ['Dentistry', '🦷', 'dentistry'],
  ['Veterinary Medicine', '🐾', 'veterinary medicine'],
  ['Pediatrics', '👶', 'pediatrics'],
  ['Surgery', '🩺', 'surgery textbook'],
  ['Mental Health', '🧘', 'mental health psychology'],
  ['Nutrition', '🥗', 'nutrition'],
  ['Yoga & Meditation', '🧘‍♀️', 'yoga meditation'],
  ['First Aid', '⛑️', 'first aid'],
  ['Anthropology', '🗿', 'anthropology'],
  ['Archaeology', '⛏️', 'archaeology'],
  ['Sociology', '👥', 'sociology'],
  ['Geography', '🗺️', 'geography'],
  ['Political Science', '🏛️', 'political science'],
  ['International Relations', '🤝', 'international relations'],
  ['Public Administration', '📋', 'public administration'],
  ['Criminology', '🕵️', 'criminology'],
  ['Journalism', '📰', 'journalism'],
  ['Media Studies', '📺', 'media studies'],
  ['Communication Skills', '🗨️', 'communication skills'],
  ['Library Science', '📇', 'library science'],
  ['Linguistics', '🔤', 'linguistics'],
  ['Creative Writing', '✍️', 'creative writing'],
  ['Essays', '📄', 'essays collection'],
  ['Speeches', '🎤', 'famous speeches'],
  ['Letters & Diaries', '💌', 'letters diaries'],
  ['Mythology', '🐉', 'mythology'],
  ['Folklore & Fairy Tales', '🧚', 'folklore fairy tales'],
  ['World Religions', '🛐', 'world religions comparative'],
  ['Buddhism', '☸️', 'buddhism'],
  ['Islamic Studies', '☪️', 'islamic studies'],
  ['Christian Theology', '✝️', 'christian theology'],
  ['Hinduism', '🕉️', 'hinduism'],
  ['Judaism', '✡️', 'judaism'],
  ['Ancient History', '🏺', 'ancient history'],
  ['Medieval History', '🏰', 'medieval history'],
  ['Renaissance History', '🎻', 'renaissance history'],
  ['World War History', '🎖️', 'world war history'],
  ['African History', '🌍', 'african history'],
  ['Asian History', '🏯', 'asian history'],
  ['European History', '🏰', 'european history'],
  ['American History', '🗽', 'american history'],
  ['Egyptology', '𓂀', 'ancient egypt'],
  ['Classical Studies', '🏛️', 'classical studies greece rome'],
  ['Philosophy of Science', '🔬', 'philosophy of science'],
  ['Ethics', '⚖️', 'ethics philosophy'],
  ['Logic', '🧩', 'logic philosophy'],
  ['Stoicism', '🪨', 'stoicism'],
  ['Existentialism', '🚶', 'existentialism'],
  ['Accounting', '🧾', 'accounting'],
  ['Auditing', '🔍', 'auditing'],
  ['Taxation', '💰', 'taxation'],
  ['Banking & Finance', '🏦', 'banking finance'],
  ['Investment', '💹', 'investment'],
  ['Insurance', '🛡️', 'insurance'],
  ['Real Estate', '🏠', 'real estate'],
  ['Supply Chain', '🚚', 'supply chain logistics'],
  ['Project Management', '📅', 'project management'],
  ['Human Resources', '🧑‍💼', 'human resource management'],
  ['Sales & Advertising', '📣', 'sales advertising'],
  ['E-commerce', '🛒', 'e-commerce'],
  ['Startups', '🚀', 'startup entrepreneurship'],
  ['Leadership', '🦅', 'leadership'],
  ['Negotiation', '🤝', 'negotiation'],
  ['Public Speaking', '🎙️', 'public speaking'],
  ['Time Management', '⏰', 'time management productivity'],
  ['Photography', '📷', 'photography'],
  ['Painting & Drawing', '🖌️', 'painting drawing art'],
  ['Graphic Design', '🎨', 'graphic design'],
  ['Fashion Design', '👗', 'fashion design'],
  ['Interior Design', '🛋️', 'interior design'],
  ['Dance', '💃', 'dance'],
  ['Theatre & Film', '🎬', 'theatre film studies'],
  ['Music Theory', '🎼', 'music theory'],
  ['Chess & Games', '♟️', 'chess strategy games'],
  ['Gardening', '🌱', 'gardening'],
  ['Sailing & Aviation', '⛵', 'sailing aviation'],
  ['Automobiles', '🚗', 'automobile engineering'],
];
